### ISSUE TITLE
Orbital ordering with pyscf

### ISSUE THREAD

**Issue by HehnLukas** [block-hczhai/block2-preview#104]
To start with, I have read https://github.com/block-hczhai/block2-preview/issues/71 as well as https://block2.readthedocs.io/en/latest/tutorial/qc-hamiltonians.html#Orbital-Reordering

However, I was wondering if it is possible to use these orbital reordering methods also with the pyscf interface, as I am not sure i could do everything I am currently doing in my workflow without it.

Additionally, in the SI of https://arxiv.org/pdf/1408.5080 it states " For rapid convergence of DMRG energy, these
orbitals were were ordered as follows: S4(3p5), S10(3p5), Fe5(3d), (...)", but there is no further information on how this ordering was found. Is this one of the methods mentioned in the docs, is this something that can be arrived at through chemical intuition, or how would one come up with the best ordering for a similar situation?

Thanks!

**Comment by hczhai** [comment]
Thanks for your interest in using ``block2``.

> However, I was wondering if it is possible to use these orbital reordering methods also with the pyscf interface

I am not sure what you mean by "the pyscf interface".  If you are talking about using ``pyblock2`` and ``pyscf`` in the same Python script, that is explained in the [documentation page](https://block2.readthedocs.io/en/latest/tutorial/qc-hamiltonians.html#Orbital-Reordering) for the Python interface of ``block2``. If you are talking about "the DMRGSCF interface", it works indirectly by using the input file interface of ``block2``, so you can use the [reordering keywords](https://block2.readthedocs.io/en/latest/user/keywords.html#orbital-reordering) to control the orbital reordering. The keywords are added via ``mc.fcisolver.block_extra_keyword`` which is set to be a list of extra keywords.

> Is this one of the methods mentioned in the docs, is this something that can be arrived at through chemical intuition

The orbital ordering roughly follows the spatial location of the localized orbitals. If you use any reasonable orbital reordering methods (like the ``fiedler`` method) implemented in ``block2``, you should get something similar. If you are asking the exact orbital reordering method the authors used, then I have no idea as I am not one of the authors.

> or how would one come up with the best ordering for a similar situation?

For one-dimension or quasi-one-dimension systems, the "best ordering" is the ordering of orbitals along that dimension. For other systems with higher dimensions, there is no good definition of "best ordering". Also there is no good algorithm to find such a thing (in a reasonable time). For higher-dimension systems, the orbital reordering algorithms implemented in ``block2`` will give you some reasonable ordering that might be useful in some cases. The paper *J. Chem. Phys.* **142**, 034102 (2015) is a good reference for understanding how orbital reordering works in different systems.

**Comment by HehnLukas** [comment]
Thanks a lot! I did mean the dmrgscf interface, and i did not find the reordering keywords on the documentation. Unfortunately (for me), the fielder method is used by default in block2 I suppose, so I doubt there is much to be gained in the ordering. I was hoping this was just something I had not been using and could give me some performance gains.
