### ISSUE TITLE
nan values in two-orbital entropies

### ISSUE THREAD

**Issue by aakunitsa** [block-hczhai/block2-preview#127]
Hello,

I ran into the issue when trying to calculate two-orbital entropies using the following script (it's a simplified version of what I would like to do for a larger open-shell system):

```python
import numpy as np
from pyblock2._pyscf.ao2mo import integrals as itg
from pyblock2.driver.core import DMRGDriver, SymmetryTypes
from pyscf import gto, scf

bond_dims = [250] * 4 + [500] * 4
noises = [1e-4] * 4 + [1e-5] * 4 + [0]
thrds = [1e-10] * 8

mol = gto.M(atom="O 0 0 0; O 0 0 1.1", basis="sto3g", spin=2, symmetry=None, verbose=0)
mf = scf.ROHF(mol).run(conv_tol=1E-14)

ncas, n_elec, spin, ecore, h1e, g2e, orb_sym = itg.get_rhf_integrals(mf,  ncore=0, ncas=None, g2e_symm=8)

driver = DMRGDriver(scratch="./tmp", symm_type=SymmetryTypes.SU2, n_threads=4)
driver.initialize_system(n_sites=ncas, n_elec=n_elec, spin=spin, orb_sym=orb_sym)
mpo = driver.get_qc_mpo(h1e=h1e, g2e=g2e, ecore=ecore, iprint=0)
ket = driver.get_random_mps(tag="GS", bond_dim=250, nroots=1)

energy = driver.dmrg(mpo, ket, n_sweeps=20, bond_dims=bond_dims, noises=noises,thrds=thrds, iprint=1)

zket = driver.mps_change_to_sz(ket, "ZKET")
driver.symm_type = SymmetryTypes.SZ
driver.initialize_system(n_sites=ncas, n_elec=n_elec,
                         spin=spin, orb_sym=orb_sym)
ordm2 = driver.get_orbital_entropies(zket, orb_type=2)
print(ordm2)
```

At first, I thought it might be due to the small eigenvalues of the 2-rdm, but there's a filter in the code that discards them 
```python
ld[np.abs(ld) < 1e-14] = 0
ld = ld[ld != 0]
```
After printing `ld`, I found nan-s among the eigenvalues themselves. 

I would appreciate any advice on how to fix this. Thank you.

**Comment by hczhai** [comment]
1. As indicated in https://github.com/block-hczhai/block2-preview/discussions/115#discussioncomment-10262345, you need to add a line ``driver.align_mps_center(mps, ref=0)`` before translating an MPS from SU2 format to SZ format.
2. A non-singlet spin-adapted MPS such as the ``S = 1`` MPS used in your script has more than 1 $S_z$ components ($S_z = -1, 0, 1$ for $S = 1$). As a result, when translating it to SZ format, we need to specify a specific $S_z$ component. This is done via the ``sz`` argument of ``driver.mps_change_to_sz``, see https://block2.readthedocs.io/en/latest/api/pyblock2.html#pyblock2.driver.core.DMRGDriver.mps_change_to_sz. If you use the default ``sz=None`` then the MPS will not conserve the $S_z$ quantum number so many operations on it will not make much sense.
3. When we extract only a component of an MPS, the norm of the extracted MPS will be smaller than the norm of the original MPS. Therefore, we need to explicitly compute the ``norm**2`` of the translated MPS, and the computed PDM/ODM quantities should be scaled by ``1 / norm**2``.

The fixed script looks like the following:

```python3
driver.dmrg(...)

driver.align_mps_center(ket, ref=0)
zket = driver.mps_change_to_sz(ket, "ZKET", sz=spin)
driver.symm_type = SymmetryTypes.SZ
driver.initialize_system(n_sites=ncas, n_elec=n_elec, spin=spin, orb_sym=orb_sym)

ovlp = driver.expectation(zket, driver.get_identity_mpo(), zket)
print('OVLP =', ovlp)

assert abs(np.trace(driver.get_1pdm(zket)[0] / ovlp) - (n_elec + spin) // 2) < 1E-10
assert abs(np.trace(driver.get_1pdm(zket)[1] / ovlp) - (n_elec - spin) // 2) < 1E-10

ordm2 = driver.get_orbital_entropies(zket, orb_type=2)
print(ordm2 / ovlp)
```

**Comment by aakunitsa** [comment]
Thank you very much for the comprehensive answer. I wish the block2 manual covered those aspects of SU2 to Sz conversion.

**Comment by aakunitsa** [comment]
@hczhai I have one final question if you don't mind. If I extract the determinant expansion coefficients from the transformed MPS (via `driver.get_csf_coefficients`), should I divide them by `np.sqrt(ovlp)` to obtain the correct values?

**Comment by hczhai** [comment]
> If I extract the determinant expansion coefficients from the transformed MPS (via driver.get_csf_coefficients), should I divide them by np.sqrt(ovlp) to obtain the correct values?

Yes. Alternatively, it may be more convenient if you simply normalize the MPS before measuring its properties.

I just noticed that there was an error in my previously reply. Properties like "orbital entropy" cannot be simply scaled, because there are logarithm operations during its computation. The only way to get a good number is first normalizing the MPS, and then computing its orbital entropies. See the edited script in the previous reply.

> I wish the block2 manual covered those aspects of SU2 to Sz conversion.

I will add these into the documentation.

**Comment by aakunitsa** [comment]
Thank you for catching the error and fixing the script! That's very helpful. I hope to learn more about the internal workings of block2 so that I can better understand how you did the normalization.
