### ISSUE TITLE
Intel MKL Error

### ISSUE THREAD

**Issue by Shovan-Physics** [block-hczhai/block2-preview#128]
I installed the latest version of block2 on a machine using CentOS 7 (on python 3.11):
```
pip3.11 install block2==0.5.3rc19 --extra-index-url=https://block-hczhai.github.io/block2-preview/pypi/
```
The installation was successful. However, calling `driver.dmrg()` produces the error:
```
INTEL MKL ERROR: /data/home/shovan.dutta/.local/lib/python3.11/site-packages/block2.libs/libmkl_def.so.1: cannot open shared object file: No such file or directory.
Intel MKL FATAL ERROR: Cannot load libmkl_def.so.1.
```
The contents of `block2.lbs` are as follows:
```
libgomp-a34b3233.so.1.0.0  libmkl_avx512.so.1         libmkl_gnu_thread-76126a9d.so.1
libmkl_avx2.so.1           libmkl_core-a1f8e95a.so.1  libmkl_intel_lp64-eeafede9.so.1
```
The `site-packages` directory includes two folders:
```
mkl-2021.4.0.dist-info
mkl_include-2024.2.2.dist-info
```
Could you help diagnose the problem here? Thanks!

**Comment by Shovan-Physics** [comment]
In case it is relevant, below are all contents of the site-packages directory:
<img width="990" alt="python3 11_site_packages-min" src="https://github.com/user-attachments/assets/90c71cd8-eb4c-4ab1-bd90-d1de9b830aa2">

**Comment by hczhai** [comment]
Please send the output of ``cat /proc/cpuinfo | grep 'model name'``.

**Comment by Shovan-Physics** [comment]
It is AMD EPYC 7302 16-Core Processor.

**Comment by hczhai** [comment]
Thanks. It is an issue of Intel MKL that it cannot work properly on an AMD CPU. To make MKL work for AMD CPU, we need the following fix. Please type the following commands in a non-temporary directory in your terminal:

```bash
echo "int mkl_serv_intel_cpu_true() { return 1; }" > fixcpu.c
gcc -shared -fPIC -o libfixcpu.so fixcpu.c
export LD_PRELOAD=$PWD/libfixcpu.so
```

Then you can execute the ``block2`` scripts, and the ``libmkl_def.so.1`` error will disappear. You may add the ``export LD_PRELOAD=$PWD/libfixcpu.so`` line in your ``~/.bashrc`` (with ``$PWD`` replaced by the actual path).

**Comment by Shovan-Physics** [comment]
That worked, thanks!
