### ISSUE TITLE
Calculation of orbital entropies using MPS

### ISSUE THREAD

**Issue by tikimtikim** [block-hczhai/block2-preview#131]
Hi. 

When I calculated orbital entropies using MPS, I encountered error like:

"  File "/home/tikim/program/block2-preview/pyblock2/driver/core.py", line 4940, in get_npdm
    pdm_type * 2, op_str, True, mask=bw.b.VectorUInt16(mask)
RuntimeError: Unable to cast Python instance of type <class 'list'> to C++ type 'unsigned short'"

It seems that the problem is related to the conversion of the type of variable between python and its library with C++.

How can I solve this issue

**Comment by hczhai** [comment]
There is no orbital entropy implementation in the SU(2) mode, see https://github.com/block-hczhai/block2-preview/discussions/99.
