### ISSUE TITLE
AMD AOCL-LAPACK (libflame) compatibility

### ISSUE THREAD

**Issue by ZuweiWang** [block-hczhai/block2-preview#133]
Hi,

I have been trying to compile block2 on a server with AMD 7003 series CPUs. And block2 does not seem to support AMD libflame currently. I tried gcc 14.2.0 + aocl 4.2.0 (so blis+libflame) with 

```
cmake .. -DUSE_MKL=OFF -DBUILD_LIB=ON -DBUILD_EXE=ON -DLARGE_BOND=ON -DMPI=ON -DUSE_MKL=OFF -DF77UNDERSCORE=OFF -DCMAKE_BUILD_TYPE=Release
```
and cmake returned:
```
-- Found BLAS: /opt/aocl-aocc-4.2.0/4.2.0/aocc/lib/libblis.so  
-- Looking for cheev_
-- Looking for cheev_ - not found
-- Looking for cheev_
-- Looking for cheev_ - not found
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find LAPACK (missing: LAPACK_LIBRARIES)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindLAPACK.cmake:615 (find_package_handle_standard_args)
  CMakeLists.txt:598 (FIND_PACKAGE)
```

from CMakeError.log:
```
/opt/gcc-14.2.0/bin/gcc  -DCHECK_FUNCTION_EXISTS=cheev_ -rdynamic CMakeFiles/cmTC_9c88e.dir/CheckFunctionExists.c.o -o cmTC_9c88e  /opt/aocl-aocc-4.2.0/4.2.0/aocc/lib/libflame.so /opt/aocl-aocc-4.2.0/4.2.0/aocc/lib/libblis.so 
/usr/bin/ld: warning: libomp.so, needed by /opt/aocl-aocc-4.2.0/4.2.0/aocc/lib/libflame.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: /opt/aocl-aocc-4.2.0/4.2.0/aocc/lib/libflame.so: undefined reference to `__kmpc_end_single@VERSION'
/usr/bin/ld: /opt/aocl-aocc-4.2.0/4.2.0/aocc/lib/libflame.so: undefined reference to `__kmpc_end_master@VERSION'
/usr/bin/ld: /opt/aocl-aocc-4.2.0/4.2.0/aocc/lib/libflame.so: undefined reference to `omp_get_thread_num@VERSION'
/usr/bin/ld: /opt/aocl-aocc-4.2.0/4.2.0/aocc/lib/libflame.so: undefined reference to `omp_get_max_threads@VERSION'
/usr/bin/ld: /opt/aocl-aocc-4.2.0/4.2.0/aocc/lib/libflame.so: undefined reference to `omp_get_max_active_levels@VERSION'
/usr/bin/ld: /opt/aocl-aocc-4.2.0/4.2.0/aocc/lib/libflame.so: undefined reference to `__kmpc_single@VERSION'
/usr/bin/ld: /opt/aocl-aocc-4.2.0/4.2.0/aocc/lib/libflame.so: undefined reference to `__kmpc_omp_task_alloc@VERSION'
/usr/bin/ld: /opt/aocl-aocc-4.2.0/4.2.0/aocc/lib/libflame.so: undefined reference to `omp_get_active_level@VERSION'
/usr/bin/ld: /opt/aocl-aocc-4.2.0/4.2.0/aocc/lib/libflame.so: undefined reference to `__kmpc_barrier@VERSION'
/usr/bin/ld: /opt/aocl-aocc-4.2.0/4.2.0/aocc/lib/libflame.so: undefined reference to `__kmpc_omp_task_with_deps@VERSION'
/usr/bin/ld: /opt/aocl-aocc-4.2.0/4.2.0/aocc/lib/libflame.so: undefined reference to `__kmpc_master@VERSION'
/usr/bin/ld: /opt/aocl-aocc-4.2.0/4.2.0/aocc/lib/libflame.so: undefined reference to `__kmpc_push_num_threads@VERSION'
/usr/bin/ld: /opt/aocl-aocc-4.2.0/4.2.0/aocc/lib/libflame.so: undefined reference to `omp_get_num_threads@VERSION'
/usr/bin/ld: /opt/aocl-aocc-4.2.0/4.2.0/aocc/lib/libflame.so: undefined reference to `__kmpc_global_thread_num@VERSION'
/usr/bin/ld: /opt/aocl-aocc-4.2.0/4.2.0/aocc/lib/libflame.so: undefined reference to `__kmpc_fork_call@VERSION'
```
The aocc + aocl combination passed the cmake but still ended up with some '__kmpc' errors while compiling, which seems to be related with aocl libraries.

I was wondering if there is a plan for implementing support for AMD compiler+libraries in the future. It is well-known that Intel MKL underperforms on AMD CPUs and I am not sure how well BLAS+LAPACK could perform compared with MKL. Do you have any suggestions on the choice of math lib for compiling on AMD machines?

Many thanks!

**Comment by hczhai** [comment]
Thanks for your interest.

> The aocc + aocl combination passed the cmake but still ended up with some '__kmpc' errors while compiling, which seems to be related with aocl libraries.

In the error log of ``cmake`` you can see ``/usr/bin/ld: warning: libomp.so, needed by /opt/aocl-aocc-4.2.0/4.2.0/aocc/lib/libflame.so, not found``, so you need to make sure ``libomp.so`` can be found in the environment, which is required by your ``libflame.so``.

> I was wondering if there is a plan for implementing support for AMD compiler+libraries in the future.

As the error is not caused by ``block2``, there is nothing we can do from the ``block2`` side.

> Do you have any suggestions on the choice of math lib for compiling on AMD machines?

I have not heard of any evidence that MKL causes unacceptable performance on AMD CPUs. If you use ``block2`` with MKL, you do not need to compile the source code. You can use ``pip install block2==0.5.3rc20 --extra-index-url=https://block-hczhai.github.io/block2-preview/pypi/`` plus some additional environment settings (see https://github.com/block-hczhai/block2-preview/issues/128#issuecomment-2378275189).

**Comment by ZuweiWang** [comment]
Many thanks for your prompt reply! Yes - there was something wrong with my environment and has nothing to do with the Block2. I successfully compiled the program with AOCC/AOCL and GCC. But there seems to be a problem when using GCC 14.2.0, since the name of omp library is libgomp, so you need to declare the location of libgomp.so otherwise cmake wouldn't find it. 

Anyway, many thanks for your reply and suggestions!

**Comment by hczhai** [comment]
Thanks for the feedback!
