### ISSUE TITLE
DMRG-GIAO or DMRG NMR

### ISSUE THREAD

**Issue by 1234zou** [block-hczhai/block2-preview#142]
Dear block2 developers,

Can this PySCF [NMR functionality](https://github.com/pyscf/properties/blob/master/examples/04-nmr.py) be combined with block2, to calculate any DMRG-CASCI/CASSCF NMR chemical shielding? I do not know the details of DMRG-GIAOs, let's say, for example, if the coupled-perturbed DMRG-CI is required when calculating NMR, is it correctly taken into consideration by PySCF+block2?

Any comments or answer are welcomed. Thanks.

**Comment by hczhai** [comment]
If you are considering NMR computed using analytical gradients, it seems to me that PySCF only implements the NMR feature at the mean-field level, and it does not yet have the analytical NMR for any _internal_ post-HF method, like CCSD and CASSCF with FCI solver. Although block2 is designed with the API to support a large variety of Hamiltonians and property computations, whether an interface/combination can work depends on the format/code of the necessary NMR related integrals computed from the PySCF side for the purpose of post-HF/multi-reference methods (which does not exist, as far as I know).
