### ISSUE TITLE
usage of readwfn.py

### ISSUE THREAD

**Issue by tikimtikim** [block-hczhai/block2-preview#143]
When the MPS for StackBlock is transformed to Block2, one should use the Python script, "readwfn.py".

As I executed `readwfn.py`, I encountered an error with the message "**AttributeError: 'block2.su2.StateConnectionInfo' object has no attribute 'n_states'**".

It seems that an object from StateInfo has variables, `n_states` and `quanta` but the one from StateInfo.get_connection_ifno(l, m, r) does not have those.

I cannot spot why this error arises.

Best regards,
Tae In Kim

**Comment by hczhai** [comment]
Thanks for reporting the problem. This is fixed in commit https://github.com/block-hczhai/block2-preview/commit/062ab25f4169d5ad8066ac44d31c773204785f95.
