### ISSUE TITLE
Running Block2 with SGF symmetry using UHF orbitals

### ISSUE THREAD

**Issue by piariane** [block-hczhai/block2-preview#149]
Hi, 

I read in the tutorial for block2 for quantum chemistry hamiltonians that it is possible to run block2 with SGF symmetry on top a UHF solution, however I cannot figure out how to do this. I can use the example below to run with SGF symmetry on top of a RHF solution, but I don't know how to adapt this to the UHF case where all objects (MO coeffs, h1e, g2e, etc.) are divided into alpha and beta parts.

Do you have an example script for doing this? (Or did I miss it somewhere in the tutorial?)

Thanks, 
Pi 
```
driver = DMRGDriver(scratch="./tmp", symm_type=SymmetryTypes.SGF, n_threads=4)

driver.n_sites = ncas
g2e = driver.unpack_g2e(g2e)
orb_sym = [orb_sym[i // 2] for i in range(len(orb_sym) * 2)]
n_sites = ncas * 2

driver.initialize_system(n_sites=n_sites, n_elec=n_elec, orb_sym=orb_sym)
```

**Comment by piariane** [comment]
The motivation for running with SGF symmetry is that I would like to compute the single orbital entropies between UHF orbitals. When running with SZ symmetry, it seems that I obtain the single orbital entropies per site and not per UHF orbital.

**Comment by hczhai** [comment]
Hi,

Thanks for reporting the problem. You can call ``mf.to_ghf()`` and then ``get_ghf_integrals`` to construct the integrals:

```python3
from pyscf import gto, scf
from pyblock2._pyscf.ao2mo import integrals as itg
from pyblock2.driver.core import DMRGDriver, SymmetryTypes

mol = gto.M(atom="N 0 0 0; N 0 0 1.1", basis="sto3g", symmetry="d2h", verbose=0)
mf = scf.UHF(mol).run(conv_tol=1E-14)
ncas, n_elec, spin, ecore, h1e, g2e, orb_sym = itg.get_ghf_integrals(mf.to_ghf(),
    ncore=0, ncas=None, g2e_symm=8)

driver = DMRGDriver(scratch="./tmp", symm_type=SymmetryTypes.SGF, n_threads=4)
driver.initialize_system(n_sites=ncas, n_elec=n_elec, orb_sym=orb_sym)
mpo = driver.get_qc_mpo(h1e=h1e, g2e=g2e, ecore=ecore, iprint=1)
```

Alternatively, with the change in commit https://github.com/block-hczhai/block2-preview/commit/57e0662e2b7d87b25b44e52ea57b365380a9e842, or after the release of block2 version [0.5.4rc1](https://github.com/block-hczhai/block2-preview/releases/tag/p0.5.4rc1), you can do the following:

```python3
from pyscf import gto, scf
from pyblock2._pyscf.ao2mo import integrals as itg
from pyblock2.driver.core import DMRGDriver, SymmetryTypes

mol = gto.M(atom="N 0 0 0; N 0 0 1.1", basis="sto3g", symmetry="d2h", verbose=0)
mf = scf.UHF(mol).run(conv_tol=1E-14)
ncas, n_elec, spin, ecore, h1e, g2e, orb_sym = itg.get_uhf_integrals(mf,
    ncore=0, ncas=None, g2e_symm=8)

driver = DMRGDriver(scratch="./tmp", symm_type=SymmetryTypes.SGF, n_threads=4)

g2e = tuple(driver.unpack_g2e(x, n_sites=ncas) for x in g2e)
orb_sym = [orb_sym[i // 2] for i in range(len(orb_sym) * 2)]
n_sites = ncas * 2

driver.initialize_system(n_sites=n_sites, n_elec=n_elec, orb_sym=orb_sym)
mpo = driver.get_qc_mpo(h1e=h1e, g2e=g2e, ecore=ecore, iprint=1)
```

**Comment by piariane** [comment]
I have one question regarding the commit you linked to. Do I understand correctly that with this commit, the orbital ordering will be alpha_1,beta_1,alpha_2,beta_2, etc.?

**Comment by hczhai** [comment]
Yes. This is to match the orbital ordering used in ``pyscf.scf.GHF``. You can of course reorder the orbitals before doing DMRG.

**Comment by piariane** [comment]
Thanks. However, as far as I can see, the orbital ordering in pyscf when using GHF is not alpha_1,beta_1,alpha_2,beta_2,... but rather ordered according to the orbital energy. So following the two approaches suggested above will result in different orbital orderings. Which is not a problem, just something to be aware of. I do prefer the latter approach since it is easier to relate the calculated orbital entropies to the UHF orbitals.
