### ISSUE TITLE
Is there a distributed scratch option?

### ISSUE THREAD

**Issue by bogdanoff** [block-hczhai/block2-preview#15]
Is it possible to make each MPI process use its own scratch space?
In a configuration of 1 MPI  process per node distributed scratch wold improve the disk I/O speed and reduce needs for the local scratch size.
I'm not sure, but it looks like block2 uses shared disk scratch, which forces the usage of some network filesystems that are inventively slower than local scratch.

**Comment by hczhai** [comment]
Thanks for reporting the issue. Please have a look at this commit: https://github.com/block-hczhai/block2-preview/commit/cbd3b3c9d94c021c2ae95e612f9345c03c323fab.

Here we introduced a new keyword called ``mps_dir``. ``mps_dir`` is used to store MPS data, which must be a global scratch directory. ``prefix`` is used to store renormalized MPO operator data, which can be different from ``mps_dir``. When they are different, ``prefix`` can be either a global scratch directory or a local scratch directory.

By default, ``mps_dir`` is the same as ``prefix``, which has to be a global scratch directory.

In a typical DMRG calculation, the renormalized MPO operators consume significantly larger amount of disk storage than the MPS data. So probably the restriction that ``mps_dir`` must be global is not a big issue.

Please let me know whether this can solve you problem or not:

    mps_dir /scratch/global/...
    prefix /scratch/local/...

**Comment by bogdanoff** [comment]
Thank you for the explanation, I will try out the `mps_dir` option!
