### ISSUE TITLE
Is there a code for three-particle reduced density matrices?

### ISSUE THREAD

**Issue by dvkhokhlov** [block-hczhai/block2-preview#17]
I'm going to move my DMRGSCF/MRPT2 code from StackBlock to Block2 thanks to its outstanding efficiency. 
Unfortunately, I couldn't find an option to calculate 3-RDMs. 
Do you have any plans to implement them? 

Best wishes, 
Daniil.

**Comment by dvkhokhlov** [comment]
Thank you, it would be very useful!

**Comment by hczhai** [comment]
Hi @dvkhokhlov, the 3PDM is now available in the most recent version of ``block2`` (version 0.5.1). Please have a look at the updated documentation for its usage: https://block2.readthedocs.io/en/latest/user/basic.html#n-particle-reduced-density-matrix and let me know if you have any further questions.
