### ISSUE TITLE
von Neumann entropy

### ISSUE THREAD

**Issue by schusteritsch** [block-hczhai/block2-preview#23]
Hi, I am trying to get the van Neumann entropy (one-orbital and two-orbitals) and eventually also the mutual information between pairs of orbitals. Is this printed somewhere by block2 already or would I need to calculate this myself? I noticed there is a keyword that may control this, 'store_wfn_spectra' - the documentation says this may output the one orbital entropy to a file called sweep_wfn_entropy.npy - I couldn't find this file when running with this keyword. Was this deprecated (git grep does't find this file in the current version)?

Any advice appreciated.

**Comment by hczhai** [comment]
Thanks for your interest in ``block2``. In the following I will first try to clarify some definitions, then I will give numerical examples for how to do the computation in ``block2``.

### Definitions

The keyword ``store_wfn_spectra`` is not for computing the single orbital entropy. As the documentation suggested, it computes the bipartite entanglement entropy in the MPS at each site. This entropy is defined, for example, in Eq. (3) in [Eur. Phys. J. B (2012) 85: 168](http://dx.doi.org/10.1140/epjb/e2012-21050-3).

The one-orbital and two-orbital entropies are different from the  bipartite entanglement entropy. I think what you mean is the entropy defined in, for example, [Chemical Physics 323 (2006) 519–531](https://doi.org/10.1016/j.chemphys.2005.10.018).

### Computation

First, please make sure you ``block2`` is manually compiled from the most recent source code, or installed using ``pip`` for the version at least ``0.5.1rc14``:

```bash
python3 -m pip install block2==0.5.1rc14 --extra-index-url=https://block-hczhai.github.io/block2-preview/pypi/
```

We use the following ``FCIDUMP`` as an example:

```bash
wget https://raw.githubusercontent.com/block-hczhai/block2-preview/master/data/N2.STO3G.FCIDUMP
```

Create an input file ``dmrg.conf`` with the following content:

```bash
sym d2h
orbitals ./N2.STO3G.FCIDUMP
schedule default
maxM 250
maxiter 20
prefix ./tmp
num_thrds 4
noreorder
nonspinadapted
store_wfn_spectra
```

Note that ``noreorder`` and ``nonspinadapted`` keywords are necessary if you want to compute the orbital entropies. Currently there is no implementation for orbital entropies with spin-adapted DMRG. The ``store_wfn_spectra`` keyword indicates that the bipartite entanglement will be computed.

Then you can run this DMRG calculation using the command:

```bash
block2main dmrg.conf > dmrg.out
```

After the calculation finishes, you can ``grep 'WFN BIP Entanglement' dmrg.out`` to get the bipartite entanglement. A file with the path ``./tmp/sweep_wfn_entropy.npy`` stores the same bipartite entanglement information.

To get the mutual information between pairs of orbitals, first create a python script ``entropy.py`` with the following content:

```python
import numpy as np
from pyblock2.driver.core import DMRGDriver, SymmetryTypes

driver = DMRGDriver(scratch="./tmp", symm_type=SymmetryTypes.SZ, n_threads=4)
driver.read_fcidump('./N2.STO3G.FCIDUMP', pg='d2h')
driver.initialize_system(n_sites=driver.n_sites, n_elec=driver.n_elec,
    spin=driver.spin, orb_sym=driver.orb_sym)
ket = driver.load_mps(tag='KET')
imat = driver.get_orbital_interaction_matrix(ket, iprint=1)

np.save('orbital_interaction.npy', imat)

import matplotlib.pyplot as plt
plt.matshow(imat)
plt.show()
```

Then in the same folder (make sure that the previous DMRG step is finished), run this script:

```bash
python3 entropy.py
```

Then the orbital interaction (mutual information between pairs of orbitals) can be found in ``./orbital_interaction.npy``.

### Notes

1. If you cannot reproduce this, or you think the keyword ``store_wfn_spectra`` does not work, please provide the detailed information of your input and output files, etc.
2. The orbital entropy computation is an experimental feature, and we do not put it in the documentation. There is no guarantee of the correctness of the implementation. Please carefully evaluate whether the results are reasonable. Bug reports are welcome.
