### ISSUE TITLE
1-step DMRGSOC

### ISSUE THREAD

**Issue by vamshimohank** [block-hczhai/block2-preview#26]
I would like to try out the 1-step DMRGSOC. Is there an example somewhere in this repo to do 1-step DMRGSOC?  If not could we have access to the input files for the systems studied in the paper https://doi.org/10.1063/5.0107805 where you compare 1-step and 2-step ways of performing DMRGSOC. 

Thanks and Regards
Vamshi

**Comment by hczhai** [comment]
Thanks for your interest in our recent work. You should be able to find a link in the "data availability" section at page 7 in the paper [*J. Chem. Phys.* **157**, 164108 (2022)](https://doi.org/10.1063/5.0107805). The link is https://github.com/hczhai/dmrg-soc-data. If the link does not work for you or you cannot find it in the paper, please let me know.

**Comment by vamshimohank** [comment]
Thanks Huanchen for the quick reply and the link for the data files. I somehow missed that info in the paper. I could successfully run the calulation for Cu atom. 

May be it is helpful for others who might want to use this feature,one should compile block2 to deal with complex MPS by setting -DUSE_COMPLEX=ON and -DUSE_SG=ON in the cmake command. 

I guess it is even a good idea to put in the installation instructions. 

Thanks and Regards
Vamshi

**Comment by hczhai** [comment]
Thanks for the suggestion. Yes we will add the compilation instructions and tutorials for SOC in the block2 documentation in the future. Alternatively, if you use the ``pip`` binary installation, the options ``-DUSE_COMPLEX=ON`` and ``-DUSE_SG=ON`` are enabled by default.
