### ISSUE TITLE
No Orbital Rotation

### ISSUE THREAD

**Issue by dking072** [block-hczhai/block2-preview#31]
Hello,

I have noticed that when using the PySCF interface with mcscf.CASCI() and using dmrgscf.DMRGCI() fcisolvers, the orbitals I enter (mc.mo_coeff before mc.kernel()) are not identical to the orbitals I get out (mc.mo_coeff after mc.kernel()). It is not clear to me from the documentation which orbitals I am getting out, especially when doing a state-averaged calculation (e.g. using mcscf.state_average_mix_).

I presume that mc.mo_coeffs[mc.ncore:mc.ncore+mc.ncas] should correspond to the active orbitals corresponding to the 1pdm.npy and 2pdm.npy files. But is there a way to get the 1pdm and 2pdm printed out in the basis I put in? I have tried playing with mc.canonicalization and mc.natorb but this does not seem to do anything.

I can of course undo any rotation of the active space, but it appears that even in SA-DMRGCI some orbitals are being rotated out of the active space to form the final set of coefficients Cfinal (as I have found evaluating the SVD of Cfinal^T S Cinitial), maybe due to some canonicalization?

Thank you for any help you can provide.

**Comment by hczhai** [comment]
Thanks for the report. Maybe I did not fully understand your question but I cannot reproduce what you said. For example, the following script is not generating any error:

```python3
mc = mcscf.CASCI(mf, 6, 8)
mc.canonicalization = False
a = mf.mo_coeff
mc.kernel(mf.mo_coeff)
b = mc.mo_coeff
assert np.linalg.norm(a - b) == 0.0
```

It might be helpful if you can provide a concrete example script to substantiate your observation.

**Comment by dking072** [comment]
Okay, sorry to bother you -- after checking it seems that I was resetting my mc object when adding the DMRG solvers via the mc._scf object, which did not pass my rearranged initial orbitals (contained in mc.mo_coeff) to the final mc object I called mc.kernel() on. So of course the two orbital spaces were different.

Thank you!
