### ISSUE TITLE
Example from documentation gives WARN: DMRG executable file for nevptsolver is the same to the executable file for DMRG solver.

### ISSUE THREAD

**Issue by HehnLukas** [block-hczhai/block2-preview#32]
Hi, first of all thanks for the detailed response here:  https://github.com/pyscf/pyscf/issues/1601

So I went ahead and installed block2, and it seems to be running. I am getting a warning when running the compress_approx nevpt2 example from [here](https://block2.readthedocs.io/en/latest/user/dmrg-scf.html#dmrg-sc-nevpt2)

`WARN: DMRG executable file for nevptsolver is the same to the executable file for DMRG solver. If they are both compiled by MPI compilers, they may cause error or random results in DMRG-NEVPT calculation.`

The code seems to run fine despite the warning, and it seems clear that it is intentional that the DMRG and DMRG NEVPT2 executables are the same. I just wanted to check to make sure this is all working correctly, and I didn't make some mistake in my installation that would give me incorrect nevpt2 results

**Comment by hczhai** [comment]
Thanks for your interest in using ``block2``.

As explained in the "Note" part in the documentation (although the docs did not explicitly refer to this WARN), for ``block2`` you can safely ignore this warning. I have updated the docs (https://github.com/block-hczhai/block2-preview/commit/ab32a59b8ffcafa1848bf1c92045b6edc7668832) to explicitly mention that this WARN can be ignored and a reference output is also added.
