### ISSUE TITLE
DMRG-SC-NEVPT2 result seems problematic for CAS(2,2)

### ISSUE THREAD

**Issue by 1234zou** [block-hczhai/block2-preview#37]
Hi, I'm doing some tests and found that the DMRG-CASSCF(2,2) based SC-NEVPT2 result of block2 is different from the result of standard CASSCF(2,2)-NEVPT2 (Of course, there is no need to perform DMRG calculations for such small active space. So this is just a test).

This problem only occurs in CAS(2,2). I've tried two versions (`block2-preview-0.5.1` and `block2-preview-p0.5.2rc4`) and this problem can be reproduced. For larger active spaces like (4,4) or (8,8), numerical results of two methods are almost identical. Here is one example: the CAS(2,2) of methane (one C-H bonding orbital and one C-H antibonding orbital)
[ch4_cas22.zip](https://github.com/block-hczhai/block2-preview/files/11183742/ch4_cas22.zip)

The DMRG-SC-NEVPT2 energy components calculated by block2 are
```
Sr    (-1)',   E = -0.00000000008124
Si    (+1)',   E = -0.00000000005290
Sijrs (0)  ,   E = -0.09775925767618
Sijr  (+1) ,   E = -0.00000000000000
Srsi  (-1) ,   E = -0.00000000000000
Srs   (-2) ,   E = -0.00000000000000
Sij   (+2) ,   E = -0.00000000000000
Sir   (0)' ,   E = -0.00000000000000
Nevpt2 Energy = -0.097759257810315
```
And there is one warning in output
```
/home/jxzou/software/dmrgscf/pyscf/dmrgscf/dmrgci.py:419: RuntimeWarning: invalid value encountered in true_divide
  twopdm /= (nelectrons-2)
```

The SC-NEVPT2 energy components calculated by CASSCF-NEVPT2 are
```
Sr    (-1)',   E = -0.00000000007663
Si    (+1)',   E = -0.00000000004147
Sijrs (0)  ,   E = -0.09775932714861
Sijr  (+1) ,   E = -0.00337510290839
Srsi  (-1) ,   E = -0.02314602815303
Srs   (-2) ,   E = -0.00952348805530
Sij   (+2) ,   E = -0.00024465569697
Sir   (0)' ,   E = -0.01382402538095
Nevpt2 Energy = -0.147872627461348
```

So, it seems that Sijr, Srsi, Srs, Sij and Sir components of block2 are problematic when calculating a very small active space like CAS(2,2).

Again, thanks for this excellent package!

**Comment by hczhai** [comment]
Hi, thanks a l lot for the report of the problem.

As you have already noticed, the error is related to the warning in ``dmrgscf/dmrgci.py`` (which is not part of ``block2``). Specifically, when you do NEVPT2, dmrgci will invoke the DMRG solver to obtain the 1pdm, 2pdm, and 3pdm, which will be used later to compute ``sijrs, sijr, srs`` etc. In the current implementation of ``dmrgscf/dmrgci.py``, the code only asks the DMRG solver to compute 3pdm, and then 1pdm and 2pdm will be obtained from a contraction of 3pdm. See https://github.com/pyscf/dmrgscf/blob/master/pyscf/dmrgscf/dmrgci.py#L418-L421

However, the formulae used there are only valid for systems with more than 2 electrons. Therefore, it will generate wrong results if you only have 2 electrons in your system. You can circumvent this problem by adding the following code at the beginning of your script:

```python3
from pyscf import dmrgscf
make_rdm123_orig = dmrgscf.DMRGCI.make_rdm123

def make_rdm123_rev(self, state, norb, nelec, link_index=None, **kwargs):
    threepdm = make_rdm123_orig(self, state, norb, nelec, link_index=None, **kwargs)[-1]
    onepdm, twopdm = self.make_rdm12(state, norb, nelec, link_index=None, **kwargs)
    return onepdm, twopdm, threepdm

dmrgscf.DMRGCI.make_rdm123 = make_rdm123_rev
```

The warning will still be there, but we will ignore the wrong ``onepdm`` and ``twopdm`` generated by ``make_rdm123_orig`` and then return the correct ``onepdm`` and ``twopdm`` computed directly from DMRG.

**Comment by 1234zou** [comment]
After adding the code you provided, the DMRG(2,2)-SC-NEVPT2 energy components are
```
Sr    (-1)',   E = -0.00000000007604
Si    (+1)',   E = -0.00000000004146
Sijrs (0)  ,   E = -0.09775932714861
Sijr  (+1) ,   E = -0.00337510290839
Srsi  (-1) ,   E = -0.02314602815303
Srs   (-2) ,   E = -0.00992263758556
Sij   (+2) ,   E = -0.00025742902769
Sir   (0)' ,   E = -0.01398407263296
Nevpt2 Energy = -0.148444597573751
```

The CASSCF-NEVPT2 correlation energy is -0.147872627461348 a.u., i.e. the energy difference is 5.7e-4 a.u. Although they are close, but I wonder where is this energy difference come from? I was expecting the energy difference may be in the magnitude of 1e-6 a.u.

**Comment by hczhai** [comment]
Sorry, there was a mistake in the code I provided previously, which is related to the different conventions of 2pdm used in different functions in ``dmrgscf/dmrgci.py``. The correct code should be:

```python3
from pyscf import dmrgscf
make_rdm123_orig = dmrgscf.DMRGCI.make_rdm123

def make_rdm123_rev(self, state, norb, nelec, link_index=None, **kwargs):
    threepdm = make_rdm123_orig(self, state, norb, nelec, link_index=None, **kwargs)[-1]
    onepdm, twopdm = self.make_rdm12(state, norb, nelec, link_index=None, **kwargs)
    twopdm = twopdm.transpose(0, 2, 3, 1)
    return onepdm, twopdm, threepdm

dmrgscf.DMRGCI.make_rdm123 = make_rdm123_rev
```

If you change your script accordingly, the energy from DMRG and FCI will match.

**Comment by 1234zou** [comment]
Great! Now the energy difference is 1e-13 a.u. Problem solved.
