### ISSUE TITLE
Block2@OpenMolcas

### ISSUE THREAD

**Issue by chburger** [block-hczhai/block2-preview#44]
It is great that Block2 with OpenMolcas now.

Unfortunately, the patched version of OpenMolcas is rather old and for instance ECPs are not available.
Is there a chance that you will adapt your code to a recent version of OpenMolcas?

Many thx in advance

Peter

**Comment by hczhai** [comment]
Thanks for the consideration of using ``block2``. I do not think this is actually an issue of ``block2``. I would suggest you post the issue to the original repo of the openMolcas-DMRG interface in https://github.com/quanp/OpenMolcas. Once that repo is updated for any newer version of openMolcas, it can be easily adapted for ``block2``.
