### ISSUE TITLE
A bug in the Green's function when orbital transformation is used

### ISSUE THREAD

**Issue by iswhy** [block-hczhai/block2-preview#46]
Hello there,

In `pyblock2/gfdmrg.py`, there is a method called `greens_function` of the `GFDMRG` class. The `greens_function` method takes a parameter called `mo_coeff` which is set to `None` by default. However, when I try to supply a matrix to this parameter, the following error occurs:

`python3: <path_to_block2>/block2-preview/src/instantiation/core/../../core/parallel_tensor_functions.hpp:122: void block2::ParallelTensorFunctions<S, FL>::right_assign(const std::shared_ptr<block2::OperatorTensor<S, FL> >&, std::shared_ptr<block2::OperatorTensor<S, FL> >&) const [with S = block2::SU2Long; FL = double]: Assertion `a->rmat->data[i] == c->rmat->data[i]' failed`

My debugging attempt indicates that the error happens at line 647: `rme.init_environments(False)`.

**How to reproduce the error**
At line 1023 and 1035 of `pyblock2/gfdmrg.py`, change `mo_coeff=None` to `mo_coeff=np.eye(len(idxs))`, then just run the test calculation at the end of this file (`python gfdmrg.py`).

**Comment by hczhai** [comment]
Hi, thanks for reporting the problem. It should be fixed in https://github.com/block-hczhai/block2-preview/commit/6ab4aa7ac57612f876d59280ab7dfab802445974.

**Comment by iswhy** [comment]
Thanks for the fix Huanchen!
