### ISSUE TITLE
openmpi lib issues

### ISSUE THREAD

**Issue by naveen-dandu** [block-hczhai/block2-preview#47]
Hi Huanchen,

We have updated to newest version of block2. While running casscf calculations, I encountered the following issue.
```
  File "/lcrc/project/SEI/Naveen/DMRG/dmrgscf/new_test/test.py", line 96, in <module>
    mc.kernel([coeff, coeff])
  File "/soft/anaconda3/2023.03/envs/DMRG-mpi/lib/python3.10/site-packages/pyscf/mcscf/umc1step.py", line 460, in kernel
    _kern(self, mo_coeff,
  File "/soft/anaconda3/2023.03/envs/DMRG-mpi/lib/python3.10/site-packages/pyscf/mcscf/umc1step.py", line 247, in kernel
    e_tot, e_cas, fcivec = casscf.casci(mo, ci0, eris, log, locals())
  File "/soft/anaconda3/2023.03/envs/DMRG-mpi/lib/python3.10/site-packages/pyscf/mcscf/umc1step.py", line 492, in casci
    e_tot, e_cas, fcivec = ucasci.kernel(fcasci, mo_coeff, ci0, log,
  File "/soft/anaconda3/2023.03/envs/DMRG-mpi/lib/python3.10/site-packages/pyscf/mcscf/ucasci.py", line 110, in kernel
    e_tot, fcivec = casci.fcisolver.kernel(h1eff, eri_cas, ncas, nelecas,
  File "/soft/anaconda3/2023.03/envs/DMRG-mpi/lib/python3.10/site-packages/pyscf/dmrgscf/dmrgci.py", line 713, in kernel
    writeIntegralFile(self, h1e, eri, norb, nelec, ecore)
  File "/lcrc/project/SEI/Naveen/DMRG/dmrgscf/new_test/test.py", line 17, in write_uhf_fcidump
    from block2 import FCIDUMP, VectorUInt8
ImportError: /soft/openmpi/4.0.7/bdw/gcc-9.2/lib/libmpi.so: undefined symbol: opal_hwloc201_hwloc_get_type_depth
```
Can you please help/suggest us regarding this issue. Complete output file is attached here for your review.

[slurm-2825656.txt](https://github.com/block-hczhai/block2-preview/files/11646357/slurm-2825656.txt)

Thank you,
Naveen

**Comment by hczhai** [comment]
Hi Naveen,

In order to analyze the problem, please provide me with the following outputs:

(1) The full output of ``python3 -m pip show block2-mpi``
(2) The full output of ``ls -l /soft/openmpi/4.0.7/bdw/gcc-9.2/lib/libmpi.so``
(3) The full output of ``ldd /soft/openmpi/4.0.7/bdw/gcc-9.2/lib/libmpi.so``
(4) The full output of ``ls -l /soft/anaconda3/2023.03/envs/DMRG-mpi/lib``
(5) The full output of ``ldd /soft/anaconda3/2023.03/envs/DMRG-mpi/lib/block2.*.so``
(6) The full output of ``which mpirun``
(7) The full output of ``which block2main``

**Comment by naveen-dandu** [comment]
Hi Huanchen:

(1)
```
/soft/anaconda3/2023.03/envs/DMRG-mpi/bin/block2main
(DMRG-mpi) python3 -m pip show block2-mpi
Name: block2-mpi
Version: 0.5.1
Summary: An efficient MPO implementation of DMRG for quantum chemistry.
Home-page: https://github.com/block-hczhai/block2-preview
Author: Huanchen Zhai, Henrik R. Larsson, Seunghoon Lee, and Zhi-Hao Cui
Author-email: hczhai@ucla.edu
License: LICENSE
Location: /gpfs/fs1/home/software/anaconda3/2023.03/envs/DMRG-mpi/lib/python3.10/site-packages
Requires: mkl, numpy, psutil, scipy
Required-by:
```


(2) `lrwxrwxrwx 1 jlow lcrcsoft 17 Jan 19  2022 /soft/openmpi/4.0.7/bdw/gcc-9.2/lib/libmpi.so -> libmpi.so.40.20.7`

(3)
``` ldd /soft/openmpi/4.0.7/bdw/gcc-9.2/lib/libmpi.so
        linux-vdso.so.1 =>  (0x00007ffd71341000)
        libopen-rte.so.40 => /soft/openmpi/4.0.7/bdw/gcc-9.2/lib/libopen-rte.so.40 (0x00002b5e17adb000)
        libopen-pal.so.40 => /soft/openmpi/4.0.7/bdw/gcc-9.2/lib/libopen-pal.so.40 (0x00002b5e17d91000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00002b5e180a8000)
        libudev.so.1 => /lib64/libudev.so.1 (0x00002b5e182ac000)
        librt.so.1 => /lib64/librt.so.1 (0x00002b5e184c2000)
        libm.so.6 => /lib64/libm.so.6 (0x00002b5e186ca000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00002b5e189cc000)
        libz.so.1 => /lib64/libz.so.1 (0x00002b5e18bcf000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00002b5e18de5000)
        libc.so.6 => /lib64/libc.so.6 (0x00002b5e19001000)
        /lib64/ld-linux-x86-64.so.2 (0x00002b5e17569000)
        libcap.so.2 => /lib64/libcap.so.2 (0x00002b5e193cf000)
        libdw.so.1 => /lib64/libdw.so.1 (0x00002b5e195d4000)
        libgcc_s.so.1 => /blues/gpfs/software/centos7/spack-latest/opt/spack/linux-centos7-x86_64/gcc-6.5.0/gcc-9.2.0-pkmzczt/lib64/libgcc_s.so.1 (0x00002b5e19825000)
        libattr.so.1 => /lib64/libattr.so.1 (0x00002b5e19a3d000)
        libelf.so.1 => /lib64/libelf.so.1 (0x00002b5e19c42000)
        liblzma.so.5 => /lib64/liblzma.so.5 (0x00002b5e19e5a000)
        libbz2.so.1 => /lib64/libbz2.so.1 (0x00002b5e1a080000)
```


(4) [dmrg-mpi-lib.txt](https://github.com/block-hczhai/block2-preview/files/11647379/dmrg-mpi-lib.txt)

(5) ldd: /soft/anaconda3/2023.03/envs/DMRG-mpi/lib/block2.*.so: No such file or directory

(6) /soft/openmpi/4.0.7/bdw/gcc-9.2/bin/mpirun

(7) /soft/anaconda3/2023.03/envs/DMRG-mpi/bin/block2main

**Comment by hczhai** [comment]
Thanks for the response. Please redo (5) as ``ldd /soft/anaconda3/2023.03/envs/DMRG-mpi/lib/python3.10/site-packages/block2.*.so`` and let me know the output.

**Comment by naveen-dandu** [comment]
Sure Huanchen, please see below:
```
(DMRG-mpi) ldd /soft/anaconda3/2023.03/envs/DMRG-mpi/lib/python3.10/site-packages/block2.*.so
        linux-vdso.so.1 =>  (0x00007ffec55df000)
        librt.so.1 => /lib64/librt.so.1 (0x00002b9a09835000)
        libgomp-f7e03b3e.so.1.0.0 => /soft/anaconda3/2023.03/envs/DMRG-mpi/lib/python3.10/site-packages/block2_mpi.libs/libgomp-f7e03b3e.so.1.0.0 (0x00002b9a09a3d000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00002b9a09c54000)
        libmkl_intel_lp64-eeafede9.so.1 => /soft/anaconda3/2023.03/envs/DMRG-mpi/lib/python3.10/site-packages/block2_mpi.libs/libmkl_intel_lp64-eeafede9.so.1 (0x00002b9a09e70000)
        libmkl_core-a1f8e95a.so.1 => /soft/anaconda3/2023.03/envs/DMRG-mpi/lib/python3.10/site-packages/block2_mpi.libs/libmkl_core-a1f8e95a.so.1 (0x00002b9a0aa7e000)
        libmkl_gnu_thread-76126a9d.so.1 => /soft/anaconda3/2023.03/envs/DMRG-mpi/lib/python3.10/site-packages/block2_mpi.libs/libmkl_gnu_thread-76126a9d.so.1 (0x00002b9a0efda000)
        libmkl_avx2.so.1 => /soft/anaconda3/2023.03/envs/DMRG-mpi/lib/python3.10/site-packages/block2_mpi.libs/libmkl_avx2.so.1 (0x00002b9a10c47000)
        libmkl_avx512.so.1 => /soft/anaconda3/2023.03/envs/DMRG-mpi/lib/python3.10/site-packages/block2_mpi.libs/libmkl_avx512.so.1 (0x00002b9a13b03000)
        libmpi.so => /soft/openmpi/4.0.7/bdw/gcc-9.2/lib/libmpi.so (0x00002b9a17974000)
        libstdc++.so.6 => /blues/gpfs/software/centos7/spack-latest/opt/spack/linux-centos7-x86_64/gcc-6.5.0/gcc-9.2.0-pkmzczt/lib64/libstdc++.so.6 (0x00002b9a17cc2000)
        libm.so.6 => /lib64/libm.so.6 (0x00002b9a1809b000)
        libgcc_s.so.1 => /blues/gpfs/software/centos7/spack-latest/opt/spack/linux-centos7-x86_64/gcc-6.5.0/gcc-9.2.0-pkmzczt/lib64/libgcc_s.so.1 (0x00002b9a1839d000)
        libc.so.6 => /lib64/libc.so.6 (0x00002b9a185b5000)
        /lib64/ld-linux-x86-64.so.2 (0x00002b9a0150f000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00002b9a18983000)
        libopen-rte.so.40 => /soft/openmpi/4.0.7/bdw/gcc-9.2/lib/libopen-rte.so.40 (0x00002b9a18b87000)
        libopen-pal.so.40 => /soft/openmpi/4.0.7/bdw/gcc-9.2/lib/libopen-pal.so.40 (0x00002b9a18e3d000)
        libudev.so.1 => /lib64/libudev.so.1 (0x00002b9a19154000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00002b9a1936a000)
        libz.so.1 => /lib64/libz.so.1 (0x00002b9a1956d000)
        libcap.so.2 => /lib64/libcap.so.2 (0x00002b9a19783000)
        libdw.so.1 => /lib64/libdw.so.1 (0x00002b9a19988000)
        libattr.so.1 => /lib64/libattr.so.1 (0x00002b9a19bd9000)
        libelf.so.1 => /lib64/libelf.so.1 (0x00002b9a19dde000)
        liblzma.so.5 => /lib64/liblzma.so.5 (0x00002b9a19ff6000)
        libbz2.so.1 => /lib64/libbz2.so.1 (0x00002b9a1a21c000)

```

**Comment by hczhai** [comment]
Thanks for the response. Please provide additionally the outputs of the following commands:

(1) ``nm /soft/openmpi/4.0.7/bdw/gcc-9.2/lib/libopen-pal.so.40 | grep hwloc201_hwloc_get``
(2) ``ls -l /soft/openmpi/4.0.7/bdw/gcc-9.2/lib/libopen-pal.so.40``
(3) ``ls -l /soft/openmpi/4.0.7/bdw/gcc-9.2/lib``
(4) ``echo $LD_PRELOAD``
(5) ``module list``
(6) ``ldd /soft/anaconda3/2023.03/envs/DMRG-mpi/lib/python3.10/site-packages/mpi4py/*.so``
(7) ``python3 -c 'from mpi4py import MPI; print(1); print(MPI.COMM_WORLD.size, MPI.COMM_WORLD.rank)'``
(8) ``python3 -c 'from block2 import FCIDUMP, VectorUInt8'``
(9) ``python3 -c 'from block2 import FCIDUMP, VectorUInt8; from mpi4py import MPI; print(1); print(MPI.COMM_WORLD.size, MPI.COMM_WORLD.rank)'``
(10) ``python3 -c 'from mpi4py import MPI; print(1); print(MPI.COMM_WORLD.size, MPI.COMM_WORLD.rank); from block2 import FCIDUMP, VectorUInt8'``

**Comment by naveen-dandu** [comment]
(1) ```
00000000000c54b0 T opal_hwloc201_hwloc_get_api_version
0000000000095a30 T opal_hwloc201_hwloc_get_area_membind
0000000000095be0 T opal_hwloc201_hwloc_get_area_memlocation
00000000000cb870 T opal_hwloc201_hwloc_get_closest_objs
0000000000094b30 T opal_hwloc201_hwloc_get_cpubind
00000000000cb6d0 T opal_hwloc201_hwloc_get_depth_type
00000000000cb9a0 T opal_hwloc201_hwloc_get_largest_objs_inside_cpuset
0000000000094e30 T opal_hwloc201_hwloc_get_last_cpu_location
00000000000951f0 T opal_hwloc201_hwloc_get_membind
00000000000cb7a0 T opal_hwloc201_hwloc_get_memory_parents_depth
00000000000cb710 T opal_hwloc201_hwloc_get_nbobjs_by_depth
00000000000cb740 T opal_hwloc201_hwloc_get_obj_by_depth
0000000000094cc0 T opal_hwloc201_hwloc_get_proc_cpubind
0000000000094ef0 T opal_hwloc201_hwloc_get_proc_last_cpu_location
0000000000095620 T opal_hwloc201_hwloc_get_proc_membind
0000000000094de0 T opal_hwloc201_hwloc_get_thread_cpubind
00000000000cb6b0 T opal_hwloc201_hwloc_get_type_depth
```


(2) `lrwxrwxrwx 1 jlow lcrcsoft 22 Jan 19  2022 /soft/openmpi/4.0.7/bdw/gcc-9.2/lib/libopen-pal.so.40 -> libopen-pal.so.40.20.7
`

(3) ```
total 5527
-rwxr-xr-x 1 jlow lcrcsoft    1035 Jan 19  2022 libmca_common_dstore.la
lrwxrwxrwx 1 jlow lcrcsoft      29 Jan 19  2022 libmca_common_dstore.so -> libmca_common_dstore.so.1.0.2
lrwxrwxrwx 1 jlow lcrcsoft      29 Jan 19  2022 libmca_common_dstore.so.1 -> libmca_common_dstore.so.1.0.2
-rwxr-xr-x 1 jlow lcrcsoft   74424 Jan 19  2022 libmca_common_dstore.so.1.0.2
-rwxr-xr-x 1 jlow lcrcsoft    1065 Jan 19  2022 libmca_common_monitoring.la
lrwxrwxrwx 1 jlow lcrcsoft      35 Jan 19  2022 libmca_common_monitoring.so -> libmca_common_monitoring.so.50.10.1
lrwxrwxrwx 1 jlow lcrcsoft      35 Jan 19  2022 libmca_common_monitoring.so.50 -> libmca_common_monitoring.so.50.10.1
-rwxr-xr-x 1 jlow lcrcsoft   33832 Jan 19  2022 libmca_common_monitoring.so.50.10.1
-rwxr-xr-x 1 jlow lcrcsoft    1035 Jan 19  2022 libmca_common_ompio.la
lrwxrwxrwx 1 jlow lcrcsoft      30 Jan 19  2022 libmca_common_ompio.so -> libmca_common_ompio.so.41.19.6
lrwxrwxrwx 1 jlow lcrcsoft      30 Jan 19  2022 libmca_common_ompio.so.41 -> libmca_common_ompio.so.41.19.6
-rwxr-xr-x 1 jlow lcrcsoft   59984 Jan 19  2022 libmca_common_ompio.so.41.19.6
-rwxr-xr-x 1 jlow lcrcsoft    1017 Jan 19  2022 libmca_common_sm.la
lrwxrwxrwx 1 jlow lcrcsoft      27 Jan 19  2022 libmca_common_sm.so -> libmca_common_sm.so.40.20.0
lrwxrwxrwx 1 jlow lcrcsoft      27 Jan 19  2022 libmca_common_sm.so.40 -> libmca_common_sm.so.40.20.0
-rwxr-xr-x 1 jlow lcrcsoft   13592 Jan 19  2022 libmca_common_sm.so.40.20.0
-rwxr-xr-x 1 jlow lcrcsoft    1071 Jan 19  2022 libmpi.la
lrwxrwxrwx 1 jlow lcrcsoft      17 Jan 19  2022 libmpi.so -> libmpi.so.40.20.7
lrwxrwxrwx 1 jlow lcrcsoft      17 Jan 19  2022 libmpi.so.40 -> libmpi.so.40.20.7
-rwxr-xr-x 1 jlow lcrcsoft 1584248 Jan 19  2022 libmpi.so.40.20.7
-rwxr-xr-x 1 jlow lcrcsoft    1606 Jan 19  2022 libmpi_mpifh.la
lrwxrwxrwx 1 jlow lcrcsoft      23 Jan 19  2022 libmpi_mpifh.so -> libmpi_mpifh.so.40.20.3
lrwxrwxrwx 1 jlow lcrcsoft      23 Jan 19  2022 libmpi_mpifh.so.40 -> libmpi_mpifh.so.40.20.3
-rwxr-xr-x 1 jlow lcrcsoft  601200 Jan 19  2022 libmpi_mpifh.so.40.20.3
-rwxr-xr-x 1 jlow lcrcsoft    1577 Jan 19  2022 libmpi_usempi_ignore_tkr.la
lrwxrwxrwx 1 jlow lcrcsoft      35 Jan 19  2022 libmpi_usempi_ignore_tkr.so -> libmpi_usempi_ignore_tkr.so.40.20.0
lrwxrwxrwx 1 jlow lcrcsoft      35 Jan 19  2022 libmpi_usempi_ignore_tkr.so.40 -> libmpi_usempi_ignore_tkr.so.40.20.0
-rwxr-xr-x 1 jlow lcrcsoft   39552 Jan 19  2022 libmpi_usempi_ignore_tkr.so.40.20.0
-rwxr-xr-x 1 jlow lcrcsoft    1678 Jan 19  2022 libmpi_usempif08.la
lrwxrwxrwx 1 jlow lcrcsoft      27 Jan 19  2022 libmpi_usempif08.so -> libmpi_usempif08.so.40.21.1
lrwxrwxrwx 1 jlow lcrcsoft      27 Jan 19  2022 libmpi_usempif08.so.40 -> libmpi_usempif08.so.40.21.1
-rwxr-xr-x 1 jlow lcrcsoft  314480 Jan 19  2022 libmpi_usempif08.so.40.21.1
-rwxr-xr-x 1 jlow lcrcsoft     993 Jan 19  2022 libompitrace.la
lrwxrwxrwx 1 jlow lcrcsoft      23 Jan 19  2022 libompitrace.so -> libompitrace.so.40.20.0
lrwxrwxrwx 1 jlow lcrcsoft      23 Jan 19  2022 libompitrace.so.40 -> libompitrace.so.40.20.0
-rwxr-xr-x 1 jlow lcrcsoft   22456 Jan 19  2022 libompitrace.so.40.20.0
-rwxr-xr-x 1 jlow lcrcsoft     999 Jan 19  2022 libopen-pal.la
lrwxrwxrwx 1 jlow lcrcsoft      22 Jan 19  2022 libopen-pal.so -> libopen-pal.so.40.20.7
lrwxrwxrwx 1 jlow lcrcsoft      22 Jan 19  2022 libopen-pal.so.40 -> libopen-pal.so.40.20.7
-rwxr-xr-x 1 jlow lcrcsoft 1573016 Jan 19  2022 libopen-pal.so.40.20.7
-rwxr-xr-x 1 jlow lcrcsoft    1050 Jan 19  2022 libopen-rte.la
lrwxrwxrwx 1 jlow lcrcsoft      22 Jan 19  2022 libopen-rte.so -> libopen-rte.so.40.20.7
lrwxrwxrwx 1 jlow lcrcsoft      22 Jan 19  2022 libopen-rte.so.40 -> libopen-rte.so.40.20.7
-rwxr-xr-x 1 jlow lcrcsoft  844104 Jan 19  2022 libopen-rte.so.40.20.7
-rwxr-xr-x 1 jlow lcrcsoft   83169 Jan 19  2022 mpi.mod
-rwxr-xr-x 1 jlow lcrcsoft    5929 Jan 19  2022 mpi_ext.mod
-rwxr-xr-x 1 jlow lcrcsoft  102656 Jan 19  2022 mpi_f08.mod
-rwxr-xr-x 1 jlow lcrcsoft    1645 Jan 19  2022 mpi_f08_callbacks.mod
-rwxr-xr-x 1 jlow lcrcsoft    9919 Jan 19  2022 mpi_f08_ext.mod
-rwxr-xr-x 1 jlow lcrcsoft   50494 Jan 19  2022 mpi_f08_interfaces.mod
-rwxr-xr-x 1 jlow lcrcsoft    2039 Jan 19  2022 mpi_f08_interfaces_callbacks.mod
-rwxr-xr-x 1 jlow lcrcsoft   10689 Jan 19  2022 mpi_f08_types.mod
-rwxr-xr-x 1 jlow lcrcsoft    1186 Jan 19  2022 ompi_monitoring_prof.la
-rwxr-xr-x 1 jlow lcrcsoft   22504 Jan 19  2022 ompi_monitoring_prof.so
drwxr-sr-x 2 jlow lcrcsoft   16384 Jan 19  2022 openmpi
drwxr-sr-x 2 jlow lcrcsoft    4096 Jan 19  2022 pkgconfig
drwxr-sr-x 2 jlow lcrcsoft    4096 Jan 19  2022 pmix
-rwxr-xr-x 1 jlow lcrcsoft   50548 Jan 19  2022 pmpi_f08_interfaces.mod
```

(4) echo $LD_PRELOAD **_"showed nothing:_**


(5) (DMRG-mpi) module list
```

Currently Loaded Modules:
  1) StdEnv   2) orca/5.0.1   3) gcc/9.2.0-pkmzczt   4) anaconda3/2023.03

Inactive Modules:
  1) openmpi/4.1.1-bebop-wyxgqtb   2) intel-mkl/2017.3.196-v7uuj6z
```


(6)```
 /soft/anaconda3/2023.03/envs/DMRG-mpi/lib/python3.10/site-packages/mpi4py/MPI.cpython-310-x86_64-linux-gnu.so:
        linux-vdso.so.1 =>  (0x00007ffcfb725000)
        libdl.so.2 => /usr/lib64/libdl.so.2 (0x00002b1698741000)
        libmpi.so.40 => /gpfs/fs1/software/centos7/spack-latest/opt/spack/linux-centos7-x86_64/gcc-9.2.0/openmpi-4.1.1-ckyrlu7/lib/libmpi.so.40 (0x00002b1698945000)
        libpthread.so.0 => /usr/lib64/libpthread.so.0 (0x00002b1698e2a000)
        libc.so.6 => /usr/lib64/libc.so.6 (0x00002b1699046000)
        /lib64/ld-linux-x86-64.so.2 (0x00002b1698194000)
        libgpfs.so => /usr/lib64/libgpfs.so (0x00002b1699414000)
        libpsm2.so.2 => /usr/lib64/libpsm2.so.2 (0x00002b169962a000)
        libopen-rte.so.40 => /gpfs/fs1/software/centos7/spack-latest/opt/spack/linux-centos7-x86_64/gcc-9.2.0/openmpi-4.1.1-ckyrlu7/lib/libopen-rte.so.40 (0x00002b16998be000)
        libopen-orted-mpir.so => /gpfs/fs1/software/centos7/spack-latest/opt/spack/linux-centos7-x86_64/gcc-9.2.0/openmpi-4.1.1-ckyrlu7/lib/libopen-orted-mpir.so (0x00002b1699be2000)
        libopen-pal.so.40 => /gpfs/fs1/software/centos7/spack-latest/opt/spack/linux-centos7-x86_64/gcc-9.2.0/openmpi-4.1.1-ckyrlu7/lib/libopen-pal.so.40 (0x00002b1699de5000)
        libpmi2.so.0 => /usr/lib64/libpmi2.so.0 (0x00002b169a23f000)
        libpmi.so.0 => /usr/lib64/libpmi.so.0 (0x00002b169a457000)
        librt.so.1 => /usr/lib64/librt.so.1 (0x00002b169a65d000)
        libm.so.6 => /usr/lib64/libm.so.6 (0x00002b169a865000)
        libutil.so.1 => /usr/lib64/libutil.so.1 (0x00002b169ab67000)
        libz.so.1 => /gpfs/fs1/software/centos7/spack-latest/opt/spack/linux-centos7-x86_64/gcc-9.2.0/zlib-1.2.11-j3zdmzq/lib/libz.so.1 (0x00002b169ad6a000)
        libhwloc.so.15 => /gpfs/fs1/software/centos7/spack-latest/opt/spack/linux-centos7-x86_64/gcc-9.2.0/hwloc-2.5.0-2sa7scw/lib/libhwloc.so.15 (0x00002b169af81000)
        libevent_core-2.1.so.7 => /gpfs/fs1/software/centos7/spack-latest/opt/spack/linux-centos7-x86_64/gcc-9.2.0/libevent-2.1.12-e6xzha3/lib/libevent_core-2.1.so.7 (0x00002b169b1dd000)
        libevent_pthreads-2.1.so.7 => /gpfs/fs1/software/centos7/spack-latest/opt/spack/linux-centos7-x86_64/gcc-9.2.0/libevent-2.1.12-e6xzha3/lib/libevent_pthreads-2.1.so.7 (0x00002b169b415000)
        libnuma.so.1 => /gpfs/fs1/software/centos7/spack-latest/opt/spack/linux-centos7-x86_64/gcc-9.2.0/numactl-2.0.14-lgxzfqo/lib/libnuma.so.1 (0x00002b169b618000)
        libgcc_s.so.1 => /blues/gpfs/software/centos7/spack-latest/opt/spack/linux-centos7-x86_64/gcc-6.5.0/gcc-9.2.0-pkmzczt/lib64/libgcc_s.so.1 (0x00002b169b823000)
        libslurm.so.32 => /usr/lib64/libslurm.so.32 (0x00002b169ba3b000)
        libpciaccess.so.0 => /gpfs/fs1/software/centos7/spack-latest/opt/spack/linux-centos7-x86_64/gcc-6.5.0/libpciaccess-0.13.5-gzflpyp/lib/libpciaccess.so.0 (0x00002b169bddc000)
        libxml2.so.2 => /gpfs/fs1/software/centos7/spack-latest/opt/spack/linux-centos7-x86_64/gcc-9.2.0/libxml2-2.9.10-edc7dyn/lib/libxml2.so.2 (0x00002b169bfe5000)
        liblzma.so.5 => /gpfs/fs1/software/centos7/spack-latest/opt/spack/linux-centos7-x86_64/gcc-9.2.0/xz-5.2.5-4drklsg/lib/liblzma.so.5 (0x00002b169c348000)
        libiconv.so.2 => /gpfs/fs1/software/centos7/spack-latest/opt/spack/linux-centos7-x86_64/gcc-9.2.0/libiconv-1.16-lgagwi6/lib/libiconv.so.2 (0x00002b169c56e000)
/soft/anaconda3/2023.03/envs/DMRG-mpi/lib/python3.10/site-packages/mpi4py/dl.cpython-310-x86_64-linux-gnu.so:
        linux-vdso.so.1 =>  (0x00007fffc49dd000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00002b10193f0000)
        libc.so.6 => /lib64/libc.so.6 (0x00002b10195f4000)
        /lib64/ld-linux-x86-64.so.2 (0x00002b1018fc9000)
```

(7) ```
1
1 0
```

(8)` **_"showed nothing:_**`

(9) ```
1
1 0
```

(10) ```
1
1 0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /soft/openmpi/4.0.7/bdw/gcc-9.2/lib/libmpi.so: undefined symbol: opal_hwloc201_hwloc_get_type_depth
```

**Comment by hczhai** [comment]
Thanks for the detailed information. I see the problem now.

From (5) we can see that in your system there are two versions of openmpi: 4.0.7 and 4.1.1, which is the source of the problem.
From (6) we can see that your package mpi4py is linked to openmpi 4.1.1 (but block2 is linked to openmpi 4.0.7).
From (7) we see that in a python script if you only have mpi4py, it can work properly.
From (8) we see that in a python script if you only have block2, it can work properly (no error printed).
(9) and (10) are the cases when you have both block2 and mpi4py. But they are linked to different versions of openmpi, which cannot coexist.
From (9) we see that if you first import block2, mpi4py can still work.
From (10) we see that if you first import mpi4py, block2 will be affected and it cannot work.

Based on the above analysis, a simple solution can be: adding a line ``import block2`` at the very beginning of your python script: ``/lcrc/project/SEI/Naveen/DMRG/dmrgscf/new_test/test.py`` then rerun the script.

Let me know if this can work.

**Comment by naveen-dandu** [comment]
Thanks Huanchen, it worked! :)
