### ISSUE TITLE
Mixing casci and orbital ordering

### ISSUE THREAD

**Issue by cvjjm** [block-hczhai/block2-preview#5]
I am trying to use the `casci` keyword with three integers specifying the occupied, active, and virtual space size to use block2 as a CAS solver. I do get the correct energies out for some small test cases if and only if also set `noreorder` in the input file. With any other orbital reordering option I get completely bogus energies. 
Maybe the reordering is applied _before_ the active space is selected?

**Comment by hczhai** [comment]
Thanks for pointing out the issue.
This should now be fixed: https://github.com/block-hczhai/block2-preview/commit/a030f416b6c5ca135cb3dbb07294559463c26835

**Comment by cvjjm** [comment]
Great!
