### ISSUE TITLE
Controlling the Krylov space dimension for the TDVP (tangent space) time-evolution from a Python code

### ISSUE THREAD

**Issue by iswhy** [block-hczhai/block2-preview#50]
Hi Huanchen,

this is more of a request than a bug report, could you possibly make the size of the Krylov space (used in TDVP time-evolution) input to the `TimeEvolution` Python class? I see that there is a C++ function `expo_apply` (defined in `src/core/complex_matrix_functions.hpp`) that accepts a parameter called `deflation_max_size` which I suppose is the Krylov space size. But there doesn't seem to be a way to control the Krylov space dimension from the Python side.

Thanks.

**Comment by hczhai** [comment]
The option should be available in this commit: https://github.com/block-hczhai/block2-preview/commit/6293ceb4cc98ae18a578880a59e571b7f8724b2d.

**Comment by iswhy** [comment]
Thanks, I can now change the Krylov space dimension.
