### ISSUE TITLE
ValueError: Unrecognized keys ({'bogoliubov'})

### ISSUE THREAD

**Issue by ywlds** [block-hczhai/block2-preview#51]
Hi @hczhai @zhcui, 
I am wondering if we can not solve it when we set bogoliubov to be True for the code.
[test2dHubbard.txt](https://github.com/block-hczhai/block2-preview/files/11882651/test2dHubbard.txt)
Thank you in advance,

Traceback (most recent call last):
  File "/opt/tiger/miniconda3/envs/python38/bin/block2main", line 61, in <module>
    dic = parse(fin)
  File "/opt/tiger/miniconda3/envs/python38/lib/python3.8/site-packages/pyblock2/driver/parser.py", line 231, in parse
    raise ValueError("Unrecognized keys (%s)" % diff)
ValueError: Unrecognized keys ({'bogoliubov'})
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[1493,1],0]

  Exit code:    1
--------------------------------------------------------------------------

**Comment by ywlds** [comment]
> The block2 code does not support bogoliubov type calculation. You can try the stackblock.

So in fact, in this work "Ground-state phase diagram of the three-band Hubbard model from density matrix", the DMRG solver is also stackblock?

**Comment by zhcui** [comment]
> > The block2 code does not support bogoliubov type calculation. You can try the stackblock.
> 
> So in fact, in this work "Ground-state phase diagram of the three-band Hubbard model from density matrix", the DMRG solver is also stackblock?

Yes. block2 is developed in recent years.

**Comment by ywlds** [comment]
> > > The block2 code does not support bogoliubov type calculation. You can try the stackblock.
> > 
> > 
> > So in fact, in this work "Ground-state phase diagram of the three-band Hubbard model from density matrix", the DMRG solver is also stackblock?
> 
> Yes. block2 is developed in recent years.

Thank you for the fast relpy.
