### ISSUE TITLE
[Question] Get CI coefficients

### ISSUE THREAD

**Issue by davidsousarj** [block-hczhai/block2-preview#52]
Hi. I am trying to get the determinant coefficients from a DMRG-CI calculation using PySCF.

I was first using stackBlock, but someone at this Github page recommended me to use Block2, as it would be easier to do using that:

https://github.com/pyscf/pyscf/issues/357

Unlike the standard PySCF FCI Solver, when I use the DMRG solver, the object `mycas.ci` does not contain the `FCIVector` objects with the determinant coefficients. It is just a iterator `range(0, nroots)`.

How can I get the determinant coefficients using Block2?

**Comment by hczhai** [comment]
Hi @davidsousarj,

You can use the following script to get the dominant determinant coefficients from a DMRG-CASCI calculation:

```python3

from pyscf import gto, scf, lib, mcscf, dmrgscf
import os

lib.param.TMPDIR = os.path.abspath('./tmp')
if not os.path.exists(lib.param.TMPDIR):
    os.mkdir(lib.param.TMPDIR)

dmrgscf.settings.BLOCKEXE = os.popen("which block2main").read().strip()
dmrgscf.settings.MPIPREFIX = ''

mol = gto.M(atom='C 0 0 0; C 0 0 1.2425', basis='ccpvdz', symmetry='d2h', verbose=4, max_memory=10000)
mf = scf.RHF(mol).run()

det_cutoff = 0.001

mc = mcscf.CASCI(mf, 8, 8)
mc.fcisolver = dmrgscf.DMRGCI(mol, maxM=1000, tol=1E-10)
mc.fcisolver.runtimeDir = lib.param.TMPDIR
mc.fcisolver.scratchDirectory = lib.param.TMPDIR
mc.fcisolver.threads = int(os.environ.get("OMP_NUM_THREADS", 4))
mc.fcisolver.memory = int(mol.max_memory / 1000) # mem in GB
mc.fcisolver.block_extra_keyword = ['nonspinadapted', 'noreorder', 'sample %s' % det_cutoff]
mc.kernel()

import numpy as np

occ_str = "0ab2"
dets = np.load(lib.param.TMPDIR + '/node0/sample-dets.npy')
vals = np.load(lib.param.TMPDIR + '/node0/sample-vals.npy')
idx = np.argsort(np.abs(vals))[::-1]
print("\nSum of weights of computed DET = %20.15f (cutoff = %.2g)\n" % ((vals ** 2).sum(), det_cutoff))
for ii, ix in enumerate(idx):
    det = ''.join([occ_str[x] for x in dets[ix]])
    print("DET %10d" % ii, det, " = %20.15f" % vals[ix])
```

Note:

1. In DMRG we normally need to handle active space including exponentially many determinants, so it does not make sense to compute the coefficients of all determinants. Instead, in ``block2`` you can set a threshold ``det_cutoff``, and it will only find the determinants and their coefficients when the absolute value of the coefficient is above the given threshold.
2. You can set the threshold to zero or a very small number for small systems to get the complete CI vector, but for larger systems this will consume exponential amount of memory and CPU time. For most systems ``det_cutoff = 0.01 ~ 0.001`` should have a reasonable polynomial complexity.

**Comment by davidsousarj** [comment]
@hczhai is it necessary to the calculation be non spin-adapted?

**Comment by davidsousarj** [comment]
I am not sure whether this will be useful for me. My goal was getting the full CI coefficients (in the FCIVector PySCF format). I have to make small perturbations in the coefficients and then manually recalculate the energy using PySCF (I ask PySCF to calculate the density matrix of the perturbed state and it requires the CI coefficients).

Also, I have to calculate the density matrix elements, not only for the ground state but also for the excited states (the other nroots). With the conventional PySCF FCI solver, I have just to specify the FCIVector associated with the state to calculate the density matrix:

`dm1 = mycas.fcisolver.make_rdm1(mycas.ci[iroot], norb=mycas.ncas, nelec=mycas.nelec)`

How can I do that using Block2? (Get the density matrix elements for the excited states)

**Comment by hczhai** [comment]
> Is it necessary to the calculation be non spin-adapted?

It is not necessary. The non-spin-adapted DMRG was used in the previous example since the determinant (DET) themselves are not spin-adapted, and you said that you want determinants. If you use spin-adapted DMRG, the computed coefficients will be the coefficients of Configuration State Functions (CSFs), not DETs.

The treatment of CSFs invlovles some additional complexities, which are explained in detail in https://github.com/block-hczhai/block2-preview/issues/25.

> The full CI coefficients (in the FCIVector PySCF format)

This is impractical. As I explained previously, DMRG is only necessary when your wave function includes exponentially many determinants (or CSFs). DMRG use MPS to replace the CI vector representation to avoid the exponential scaling. Therefore, if you can get the complete CI vector, then you do not need to do DMRG. If you have to do DMRG, then the CI vector (as in pyscf's representation) must be a bad representation. Also note that the CI vector in pyscf is not spin-adapted.

> How can I do that using Block2? (Get the density matrix elements for the excited states)

You can use the following script:

```python3

from pyscf import gto, scf, lib, mcscf, dmrgscf, ao2mo
import os

lib.param.TMPDIR = os.path.abspath('./tmp')
if not os.path.exists(lib.param.TMPDIR):
    os.mkdir(lib.param.TMPDIR)

dmrgscf.settings.BLOCKEXE = os.popen("which block2main").read().strip()
dmrgscf.settings.MPIPREFIX = ''

mol = gto.M(atom='C 0 0 0; C 0 0 1.2425', basis='ccpvdz', symmetry='d2h', verbose=4, max_memory=10000)
mf = scf.RHF(mol).run()

det_cutoff = 0.001

mc = mcscf.CASCI(mf, 8, 8)
mc.fcisolver = dmrgscf.DMRGCI(mol, maxM=1000, tol=1E-10)
mc.fcisolver.runtimeDir = lib.param.TMPDIR
mc.fcisolver.scratchDirectory = lib.param.TMPDIR
mc.fcisolver.threads = int(os.environ.get("OMP_NUM_THREADS", 4))
mc.fcisolver.memory = int(mol.max_memory / 1000) # mem in GB
mc.fcisolver.block_extra_keyword = ['nonspinadapted', 'noreorder']
mc.fcisolver.nroots = 3
mc.kernel()

import numpy as np
h1e, ecore = mc.get_h1eff()
g2e = ao2mo.restore(1, mc.get_h2eff(), mc.ncas)

for i in range(3):
    pdm1, pdm2 = mc.fcisolver.make_rdm12(mc.ci[i], norb=mc.ncas, nelec=mc.nelecas)
    print('State %d energy from pdms = %20.15f' % (i, np.einsum('ij,ij->', pdm1, h1e)
        + 0.5 * np.einsum('ijkl,ijkl->', pdm2, g2e) + ecore))
```

**Comment by davidsousarj** [comment]
Thank you very much!
