### ISSUE TITLE
spin correlation calculations

### ISSUE THREAD

**Issue by naveen-dandu** [block-hczhai/block2-preview#54]
Dear Huanchen, 
I am trying to test 3 Ru atoms in chain, each 5 Angstrom apart. It is taking forever to finish the calculating integrals. Can you please let me know how to speed up the calculations? Please find attached input and output files.
Thank you,
Naveen

**Comment by hczhai** [comment]
Hi, the input and output files you attached are irrelevant to your description of the problem.

**Comment by naveen-dandu** [comment]
Sorry Huanchen,

please see attached.
[slurm-2882628.out.txt](https://github.com/block-hczhai/block2-preview/files/11971736/slurm-2882628.out.txt)
[test.py.txt](https://github.com/block-hczhai/block2-preview/files/11971737/test.py.txt)

**Comment by hczhai** [comment]
Running ab initio DMRG with 120 orbitals and bond dimension 250 will not generate any meaningful results. Also ``n_threads=2`` will not give you any reasonable speed. Note that DMRG is almost the most expensive method for electronic structure problems.
I suggest you first do some computations using other cheaper methods to get an idea of the tested system, and carefully read the paper _J. Chem. Phys._ **142**, 034102 (2015) to understand the current capability and the limitations of the DMRG algorithms.
