### ISSUE TITLE
assertion error while doing casscf

### ISSUE THREAD

**Issue by naveen-dandu** [block-hczhai/block2-preview#55]
Dear Huanchen,

I am getting an error while performing casscf calculations to get magnetization values. Can you please help me with this issue. Please see attached.

[slurm-2882827.out.txt](https://github.com/block-hczhai/block2-preview/files/11971770/slurm-2882827.out.txt)

thank you,
Naveen

**Comment by hczhai** [comment]
Hi, thanks for providing the files. The parameter ``cas_list=list(range(829, 836))`` will not work because the core and virtual part of the system must have an even number of electrons. It should be at least ``cas_list=list(range(829, 837))`` according to your output.

**Comment by naveen-dandu** [comment]
Thanks Huanchen, thanks for the help. 
I am now having problems with memory error. Irrespective of specifying more mem in input file, it is always using 4000MB of max_mem? how can i request more memory?

Please see attached output file.
[slurm-2885644.out.txt](https://github.com/block-hczhai/block2-preview/files/11983154/slurm-2885644.out.txt)


Thank you,
Naveen

**Comment by hczhai** [comment]
The error is from ``pyscf`` so you may look at the ``pyscf`` documentation https://pyscf.org/user/gto.html#other-parameters.
