### ISSUE TITLE
RASSCF in block2

### ISSUE THREAD

**Issue by JangidBhavnesh** [block-hczhai/block2-preview#56]
Is there a way to perform the RASSCF in block2? If yes, can developer provide a sample input file?

Thanks

**Comment by hczhai** [comment]
As DMRG-CASSCF with block2 was implemented through the dmrgscf extension of pyscf, which does not support RASSCF. So currently we cannot do this in block2.

**Comment by JangidBhavnesh** [comment]
But in this paper (https://arxiv.org/abs/2305.08184) authors did mentioned that they used RASSCF in block2. Perhaps it might be private repo?

**Comment by hczhai** [comment]
(1) The paper you linked did not say any RASSCF. What it did is just RASCI with MPS: this is indeed supported in block2.
(2) The example scripts for that paper can be found in https://github.com/seunghoonlee89/pyxray_preview (a public repo).
