### ISSUE TITLE
Available Spin-orbit formalism

### ISSUE THREAD

**Issue by JangidBhavnesh** [block-hczhai/block2-preview#57]
Which all spin-orbit formalism are available in block2?

**Comment by hczhai** [comment]
Thanks for your interest in block2. You can find block2 DMRG-SOC algorithms in the paper [J. Chem. Phys. 157, 164108 (2022)](https://doi.org/10.1063/5.0107805). The scripts used for generating data in that paper can be found in https://github.com/hczhai/dmrg-soc-data.
