### ISSUE TITLE
[Question] spin-resolved density matrix from PySCF 

### ISSUE THREAD

**Issue by davidsousarj** [block-hczhai/block2-preview#58]
Hi.

I know I can obtain the spin-traced density matrices from a DMRG calculation in PySCF/Block2 by using

`dm1, dm2 = mycas.fcisolver.make_rdm12(mycas.ci, norb=mycas.ncas, nelec=mycas.nelecas)`

However, I need the density matrices per spin component, `(dm1alpha, dm1beta), (dm2aa, dm2ab, dm2bb)`.

I tried to use the `make_rdm12s` method in PySCF, which would be the natural way to do that for a MCSCF calculation, but I got the following error:

```
Traceback (most recent call last):
  File "/home/david/dmrg.py", line 74, in <module>
    d1, d2 = mycas.fcisolver.make_rdm12s(mycas.ci, norb=mycas.ncas, nelec=mycas.nelecas)
AttributeError: 'DMRGCI' object has no attribute 'make_rdm12s'. Did you mean: 'make_rdm12'?
``` 

Is there a direct way to do that using PySCF/Block2?

p.s.: I read the documentation and I noticed that the spin-resolved density matrices are supposedly saved in files within the scratch folder. However, for some reason, in my calculation the files for the 1-particle DM are not there, only the ones for the 2-particle DM. Besides, accessing those files after the calculation seems more like a hack than a direct implemented way to do it.

**Comment by hczhai** [comment]
You can follow the documentation https://block2.readthedocs.io/en/latest/user/dmrg-scf.html#unrestricted-dmrgscf to do the unrestricted CASSCF and non-spin-adapted DMRG, and then ``make_rdm12s`` will be defined.

> in my calculation the files for the 1-particle DM are not there, only the ones for the 2-particle DM

In ``pyscf``, 1pdm is computed by contracting 2pdm.

**Comment by davidsousarj** [comment]
Thank you for the response.

The `make_rdm12s` function from the link above is very useful. It loads the 2-pdm from the scratch file and transforms it in the 1-pdm. However, I tested it here and for some reason the 1-pdm generated by this method is not correct. The trace of the 1-pdm does not correspond to the correct number of electrons.

I could fix this by adding this line in my code to set Block2 to calculate explicitly the 1-pdm:

`mycas.fcisolver.block_extra_keyword.append('onepdm')`

Then I modified the function as follows:

``
def make_rdm12s(DMRGCI, state, norb, nelec, **kwargs):
    if isinstance(nelec, (int, np.integer)):
        na = nelec // 2 + nelec % 2
        nb = nelec - na
    else:
        na, nb = nelec

    file2pdm = f"2pdm-{state}-{state}.npy" if DMRGCI.nroots > 1 else "2pdm.npy"
    dm2 = np.load(os.path.join(DMRGCI.scratchDirectory, "node0", file2pdm))
    dm2 = dm2.transpose(0, 1, 4, 2, 3)
    #dm1a = np.einsum('ikjj->ki', dm2[0]) / (na - 1)
    #dm1b = np.einsum('ikjj->ki', dm2[2]) / (nb - 1)
    #return (dm1a, dm1b), dm2
    file1pdm = f"1pdm-{state}-{state}.npy" if DMRGCI.nroots > 1 else "1pdm.npy"
    dm1 = np.load(os.path.join(DMRGCI.scratchDirectory, "node0", file1pdm))
    return dm1, dm2
```
To call the function and get the DMs of the `i`-th CI root, I do: 

`(dm1a, dm1b), (dm2aa, dm2ab, dm2bb) = make_rdm12s(mycas.fcisolver, mycas.ci[i], norb=mycas.ncas, nelec=mycas.nelecas)

**Comment by davidsousarj** [comment]
Hello again.

I just realized that the there is a problem with the spin-resolved density matrices obtained Block2.

I was trying to calculate spin properties from the DMRG density matrices but I was getting wrong results. So I run calculations for one system and compared the density matrices obtained by CASCI and by DMRG.

The system has spin = 9/2, 16 orbitals and 23 electrons (na = 16, nb = 7). I used a small basis set just to quickly compare both methods.

Energy difference from the two calculations was 5e-7 hartree, which is reasonable.

Here are the results:

Trace( dm2aa + dm2ab + dm2ba + dm2bb ) = 506.0 for both of them.
Trace( dm2aa ) = 240.0 (CASCI), 129.0 (DMRG)
Trace(  dm2bb ) = 42.0 (CASCI), 129.0 (DMRG)

dm1 obtained by keyword `onepdm`:
Trace( dm1a + dm1b ) = 23.0 for both of them
Trace(  dm1a ) = 16.0 (CASCI), 11.5 (DMRG)
Trace( dm1b ) = 7.0 (CASCI), 11.5 (DMRG)

dm1 obtained by contracted dm2:
Trace( dm1a + dm1b ) = 23.0 (CASCI), 30.1 (DMRG)
Trace(  dm1a ) = 16.0 (CASCI), 8.6 (DMRG)
Trace( dm1b ) = 7.0 (CASCI), 21.5 (DMRG)

So it seems these spin resolved dm's are kind of 'averaged' and are not reliable to obtain spin properties.

**Comment by hczhai** [comment]
Hi, thanks for the report. Could you please provide a complete example script for generating this result?

**Comment by hczhai** [comment]
Without the knowledge of the input settings, I guess the problem is that you are performing the **spin-adapted** DMRG rather than the **non-spin-adapted** DMRG.

In the **spin-adapted** DMRG algorithm, the spin parameter is understood as the "total spin", which means in the calculation $S=9/2$ (rather than $S_z=9/2$). Note that $S=9/2$ has both the $S_z=-9/2$ and $S_z=9/2$ components (and other components) so it is **correct** that you get the same 1pdm and 2pdm for alpha and beta in a spin-adapted calculation. In other words, when you expect the alpha and beta properties to be different, you are considering a state with a specific projected spin $S_z$, and $S_z$ is a good quantum number only in the non-spin-adapted case. For singlet $S=S_z=0$, the 1pdm and 2pdm will match no matter it is spin-adapted DMRG or non-spin-adapted DMRG.

The CASCI result you get should be from the FCI solver in ``pyscf``, which is a determinant based implementation, so it is non-spin-adapted FCI. (Spin-adapted FCI is normally implemented using "GUGA".) You should only compare non-spin-adapted FCI and non-spin-adapted DMRG.

My reply in https://github.com/sanshar/Block/issues/56 may also be a good reference.

**Comment by davidsousarj** [comment]
The code has too many lines to write here (it took some time just to put it in a single file), but I can provide a link for the script:

https://mega.nz/file/wlsCwJ5Z#3SQRb_UrUFu9SrncyGMRuSZJRbJG08mvgkxzb9hNNQ4

**Comment by davidsousarj** [comment]
Yes, I am using the spin-adapted DMRG with is the default option. I really did not know about the details regarding total S and Sz. Thank you so much for the explanation.

So, can I obtain the correct spin properties if I just choose the non-spin adapted option in DMRG?

**Comment by hczhai** [comment]
Sure, if you follow the script for non-spin-adapted DMRG in https://block2.readthedocs.io/en/latest/user/dmrg-scf.html#unrestricted-dmrgscf you will get the expected spin resolved density matrices.
Alternatively, you can also add ``mc.fcisolver.block_extra_keyword = ["nonspinadapted"]`` in your current script to make it non-spin-adapted (in this case, the input ``spin`` will be reinterpreted as $S_z$).

**Comment by bogdanoff** [comment]
I saw the related discussion in pyscf, so cross-post here as well.
There are ways to get spin-dependent properties from spin-free RDMs, we (re)derived some of those in appendices of [10.1021/acs.jctc.1c00589](https://pubs.acs.org/doi/10.1021/acs.jctc.1c00589). 
There is also `mcscf.addons.make_spin_casdm1`  function following eq. 3 of [10.1002/qua.22320](https://onlinelibrary.wiley.com/doi/10.1002/qua.22320) to compute spin-resolved 1rdm from spin-free 2rdm.
