### ISSUE TITLE
Error importing block2

### ISSUE THREAD

**Issue by davidsousarj** [block-hczhai/block2-preview#60]
Hi. I had to install Block2 in a new machine today, and I got an error I have never seen before. While trying to run the PySCF example found in the doc page, I have got this:

```
******** Block flags ********
executable             = .../pyscf_env/bin/block2main
BLOCKEXE_COMPRESS_NEVPT= /path/to/serially/compiled/Block/block.spin_adapted
Traceback (most recent call last):
  File ".../pyscf_env/lib/python3.11/site-packages/pyscf/dmrgscf/dmrgci.py", line 1008, in block_version
    msg = check_output([blockexe, '-v'], stderr=STDOUT).decode()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../pyscf_env/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../pyscf_env/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['.../pyscf_env/bin/block2main', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/storage/home/dms7983/examples/pyscf_dmrg/example.py", line 24, in <module>
    mc.kernel(coeff)
  File ".../pyscf_env/lib/python3.11/site-packages/pyscf/mcscf/mc1step_symm.py", line 66, in kernel
    self.dump_flags()
  File ".../pyscf_env/lib/python3.11/site-packages/pyscf/mcscf/mc1step.py", line 819, in dump_flags
    self.fcisolver.dump_flags(self.verbose)
  File ".../pyscf_env/lib/python3.11/site-packages/pyscf/dmrgscf/dmrgci.py", line 244, in dump_flags
    log.info('Block version          = %s', block_version(self.executable))
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../pyscf_env/lib/python3.11/site-packages/pyscf/dmrgscf/dmrgci.py", line 1017, in block_version
    f1.write('memory 1 m\n')
  File ".../pyscf_env/lib/python3.11/tempfile.py", line 483, in func_wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
TypeError: a bytes-like object is required, not 'str'
```
It seems the error is risen just before calling the block2main executable. So I tried to execute it from the terminal and got this:

```
$ block2main
Traceback (most recent call last):
  File ".../pyscf_env/bin/block2main", line 10, in <module>
    from block2 import SZ, SU2, SZK, SU2K, SGF, DoubleFPCodec as FPCodec
ImportError: generic_type: cannot initialize type "ValuesView[Tuple[%, %]]": an object with that name is already defined
```

Even just trying to import it from python causes the same error:

```
$ python
Python 3.11.5 (main, Sep 11 2023, 13:54:46) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import block2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: generic_type: cannot initialize type "ValuesView[Tuple[%, %]]": an object with that name is already defined
```

So, I just checked Issue #36 and saw that is very similar to my problem. However, I am already using `pybind11<=2.10.2`, my version is 2.10.1.

**Comment by hczhai** [comment]
Thanks for the error report. The pybind11 issue may only happen when you compile manually. Could you send me (a) your ``cmake`` command; and (b) the output of the ``cmake`` command?

**Comment by davidsousarj** [comment]
I installed using `pip`. What do you mean by sending the command?

```
$ cmake
Usage

  cmake [options] <path-to-source>
  cmake [options] <path-to-existing-build>
  cmake [options] -S <path-to-source> -B <path-to-build>

Specify a source directory to (re-)generate a build system for it in the
current working directory.  Specify an existing build directory to
re-generate its build system.

Run 'cmake --help' for more information.
```
```
$ cmake --version
cmake version 3.26.3

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**Comment by hczhai** [comment]
OK. Sorry I did not realized that you installed using pip. Then the question is what is your ``pip install`` command? And what version of ``block2`` did you installed? You can check the version using ``python3 -m pip show block2`` or ``python3 -m pip show block2-mpi``.

**Comment by davidsousarj** [comment]
I just used `pip install block2`.

``
$ python -m pip show block2
Name: block2
Version: 0.5.1
Summary: An efficient MPO implementation of DMRG for quantum chemistry.
Home-page: https://github.com/block-hczhai/block2-preview
Author: Huanchen Zhai, Henrik R. Larsson, Seunghoon Lee, and Zhi-Hao Cui
Author-email: hczhai@ucla.edu
License: LICENSE
Location: /storage/group/evs5812/default/pyscf_env/lib/python3.11/site-packages
Requires: cmake, intel-openmp, mkl, mkl-include, numpy, psutil, pybind11, scipy
Required-by: 
```

**Comment by davidsousarj** [comment]
Oh, I see that there is already a version 0.5.2. I will install the most recent version and see whether the error still exists.

**Comment by davidsousarj** [comment]
So, I tried to install the most recent version from Github using

`pip install git+https://github.com/block-hczhai/block2-preview`

But I couldn't. Do I show the giant error message (~150 lines)?

**Comment by hczhai** [comment]
Hi, I guess that the problem is that the python version 3.11 you used is too new.
We currently do not have the precompiled binary for python 3.11. When you try ``pip`` with python 3.11, it will try to automatically compile from source in your machine, which will take hours and arbitrary error can occur.
If you can use 3.10, everything will be ok.

**Comment by davidsousarj** [comment]
Oh I see. I will have to recreate the conda environment from scratch. So, I will do this tomorrow and let you know the result.

**Comment by davidsousarj** [comment]
@hczhai today I have reset my conda environment to use python 3.10 and everything works now. Thanks!
