### ISSUE TITLE
infinite loop

### ISSUE THREAD

**Issue by mfdgroot** [block-hczhai/block2-preview#62]
Hi @hczhai,

Thank you for the updates in the latest version, super useful additions.

I'm trying to convert a singlet embedded wave function to non-singlet embedding through the python interface.
```
driver = DMRGDriver(scratch="/scratch/", symm_type=SymmetryTypes.SU2, n_threads=10,)
driver.initialize_system(n_sites=ncas, n_elec=nelecas, spin=1, orb_sym=orb_sym, singlet_embedding=True)
mpo = driver.get_qc_mpo(h1e=h1e, g2e=g2e, ecore=ecore, iprint=2)
seket = driver.get_random_mps(tag="SE", bond_dim=2000, nroots=1)
energy = driver.dmrg(mpo, ket, n_sweeps=20, iprint=2)
noseket = driver.mps_change_from_singlet_embedding(seket, "NOSE")
```
The code doesn't terminate and by throwing in print statements I can see it's stuck on this part of the code:
https://github.com/block-hczhai/block2-preview/blob/21a0570e6e89ee3f954c0366b5d45a241901788a/pyblock2/driver/core.py#L4107-L4108
The `move_left` statement does not seem to update the `cp_mps.center`.

Is there something obvious I'm missing?

**Comment by hczhai** [comment]
Thanks for reporting the problem. This should be fix in https://github.com/block-hczhai/block2-preview/commit/3f148ec582bf67abb18dcbea7c4a05f94cd428ba .
