### ISSUE TITLE
How to get the MPS in the tensor form ?

### ISSUE THREAD

**Issue by Dulsinea** [block-hczhai/block2-preview#64]
Hi, I have noticed this https://github.com/block-hczhai/block2-preview/issues/34 , but I still want to confirm whether MPS is possible.

Prior to delving into Block2, I explored the MPS format generated by the Qcmaquis program (https://github.com/qcscine/qcmaquis), which contains many blocks, each associated with distinct quantum numbers.  As far as I understand, these quantum numbers are represented as <first, second, third>, where 'first' signifies particle number, 'second' represents spin, and 'third' corresponds to irrep：
[Qcmaquis-ben-su2-mps.txt](https://github.com/block-hczhai/block2-preview/files/13246035/Qcmaquis-ben-su2-mps.txt)

**My inquiry** revolves around the possibility of converting the MPS output from the Block2 program into a format akin to that of Qcmaquis. I am particularly interested in aligning Block2's MPS output with the structure used in Qcmaquis. 

Any advice most welcome.

**Comment by hczhai** [comment]
Thanks for your interest in using block2. You can find some outputs like what you expected using the script given in https://github.com/block-hczhai/block2-preview/discussions/35. The following is the example script which transform the MPS in block2 to the one in pyblock3, and then print one of the tensors.

```python3
import numpy as np
from pyblock2._pyscf.ao2mo import integrals as itg
from pyblock2.driver.core import DMRGDriver, SymmetryTypes
from pyblock3.block2.io import MPSTools, MPOTools

from pyscf import gto, scf

mol = gto.M(atom="N 0 0 0; N 0 0 1.1", basis="sto3g", symmetry="d2h", verbose=0)
mf = scf.RHF(mol).run(conv_tol=1E-14)
ncas, n_elec, spin, ecore, h1e, g2e, orb_sym = itg.get_rhf_integrals(mf,
    ncore=0, ncas=None, g2e_symm=8)

driver = DMRGDriver(scratch="./tmp", symm_type=SymmetryTypes.SZ, n_threads=4)
driver.initialize_system(n_sites=ncas, n_elec=n_elec, spin=spin, orb_sym=orb_sym)

mpo = driver.get_qc_mpo(h1e=h1e, g2e=g2e, ecore=ecore, add_ident=False, iprint=1)

ket = driver.get_random_mps(tag="GS", bond_dim=250, nroots=1)
bond_dims = [250] * 4 + [500] * 4
noises = [1e-4] * 4 + [1e-5] * 4 + [0]
thrds = [1e-10] * 8
energies = driver.dmrg(mpo, ket, n_sweeps=5, bond_dims=bond_dims,
    noises=noises, thrds=thrds, iprint=1)
print('DMRG energy = %20.15f' % energies)

ket = driver.adjust_mps(ket, dot=1)[0]
print(ket.n_sites, ket.canonical_form)

pyket = MPSTools.from_block2(ket)
print('MPS tensor at site 1 =\n', pyket.tensors[1])
```

In the output you can see that one MPS tensor contains many blocks, one of the block is represented as

```
1 (Q=) (< N=1 SZ=1/2 PG=0 >, < N=0 SZ=0 PG=0 >, < N=1 SZ=1/2 PG=0 >) (R=) array([[[1.]]])
```

meaning that this is a 1x1x1 block (note that each MPS tensor has 3 legs). We have 3 quantum numbers for this block (corresponding to the left virtual bond, the physical bond, and the right virtual bond). The first quantum number is < N=1 SZ=1/2 PG=0 > (for the left virtual bond), which means that the particle number is N=1, the projected spin is SZ=1/2, point group irrep is PG=0. For more detailed information on the representation you can have a look at the pyblock3 documentation: https://pyblock3.readthedocs.io/en/latest/Documentation/symmetry.html.
