### ISSUE TITLE
Question regarding the block2main input file for running complex FCIDUMP

### ISSUE THREAD

**Issue by henhans** [block-hczhai/block2-preview#66]
Dear Developers,

First of all, thank you for this wonderful code. I am trying to use block2 to solve Hamiltonians with spin-orbit coupling or with complex hybridizations. I want to use the block2main directly with "block2main dmrg.conf". I generated the attached FCIDUMP with driver.write_fcidump() for a 24 spin-orbital model (here, I still use a real Hamiltonian to compare with known results), but I couldn't succeed in setting up a correct input file to run this FCIDUMP. Attached are my input file (input.txt) and the FCIDUMP file (FCIDUMP.txt); I wonder if you could guide me in setting up the correct input file. Thank you very much in advance!

Tsung-Han

[FCIDUMP.txt](https://github.com/block-hczhai/block2-preview/files/13331254/FCIDUMP.txt)
[input.txt](https://github.com/block-hczhai/block2-preview/files/13330797/input.txt)

**Comment by hczhai** [comment]
Thanks for your interest in the ``block2`` package. The two-electron part of your FCIDUMP is only defined for the first six orbitals and you have 24 orbitals, which may be problematic.

The following is an example script for generating the FCIDUMP (with spin-orbit coupling) for the (7e, 4o) active space of the F atom:

```python3
import numpy as np
from pyblock2._pyscf.ao2mo import soc_integrals as itg
from pyblock2.driver.core import DMRGDriver, SymmetryTypes
from pyscf import gto, scf, mcscf

mol = gto.M(atom='F 0 0 0',
            symmetry=False,
            basis='ccpvtz-dk', spin=1, charge=0, verbose=3)
mf = scf.newton(scf.RHF(mol).sfx2c1e()).run(conv_tol=1e-14)

ncaselec, ncas = 7, 4
ncore = (mol.nelectron - ncaselec) // 2

print('ncore = ', ncore, ' ncas = ', ncas)
mc = mcscf.CASSCF(mf, ncas, ncaselec).state_average_(np.ones(3) / 3.0).run()
mf.mo_coeff = mc.mo_coeff
dmao = mc.make_rdm1()
n_sites, n_elec, spin, ecore, gh1e, gg2e, orb_sym = \
    itg.get_rhf_somf_integrals(mf, ncore, ncas, False, dmao=dmao, amfi=False, x2c1e=True, x2c2e=True)

driver = DMRGDriver(scratch="./tmp", symm_type=SymmetryTypes.SGFCPX, n_threads=4)
driver.initialize_system(n_sites=n_sites, n_elec=n_elec, spin=0, orb_sym=orb_sym)
driver.write_fcidump(h1e=gh1e, g2e=gg2e, ecore=ecore, filename='FCIDUMP')

# The following can also be done using the input file interface ...

bond_dims = [250] * 4 + [500] * 4
noises = [1e-4] * 4 + [1e-5] * 4 + [0]
thrds = [1e-10] * 8

mpo = driver.get_qc_mpo(h1e=gh1e, g2e=gg2e, ecore=ecore, iprint=1)
ket = driver.get_random_mps(tag="KET", bond_dim=250, nroots=6)
energies = driver.dmrg(mpo, ket, n_sweeps=20, bond_dims=bond_dims, noises=noises,
    thrds=thrds, iprint=2)

e0 = np.average(energies[0:4])
e1 = np.average(energies[4:6])

au2cm = 219474.63
print("")
print("ZFS 2P  1/2 - 3/2      = %10.4f cm-1" % ((e1 - e0) * au2cm))
print("ZFS 2P  1/2 - 3/2 exp. = %10.4f cm-1" % 404.141)
# Experimental data from:
# https://physics.nist.gov/PhysRefData/Handbook/Tables/fluorinetable5.htm
```

The expected output is $393.04~\mathrm{cm}^{-1}$. It is recommended to use the python interface for SOC-DMRG. As indicated in the above script, once FCIDUMP is generated you can alternatively use the input file for running DMRG. The input file should be written as:

```
orbitals FCIDUMP
use_general_spin
use_complex
hf_occ integral
schedule default
maxM 500
maxiter 30
num_thrds 4
nroots 6
```

A bug fix https://github.com/block-hczhai/block2-preview/commit/ab3acfea4a6cecc757c1fd1f942fe05a0a186279 (or the pip version 0.5.3rc3) is required for getting the accurate number for this example (if you use the input file interface). If you use the python script interface, there is no need to apply the bug fix.

Note that the input file interface only works for real-valued two-electron integrals. If you have complex numbers in both the one- and two-electron integrals, you have to use the python interface.
