### ISSUE TITLE
Questions regarding inconsistent accuracy between pyblock2, dmrgscf, and block2main

### ISSUE THREAD

**Issue by henhans** [block-hczhai/block2-preview#68]
Dear Developers,

Thank you very much for your previous reply. I am comparing the accuracy of pyblock2, dmrgscf, and block2main on a generic custom Hamiltonian by benchmarking their ground state energy and density matrix with FCI. I notice that with the same bond dimension maxM=300, pyblock2 seems to have lower accuracy. For example, I got the following ground state energy for different approaches:
E_FCI=-22.330549358353128
E_pyblock2=-22.3300778814
E_dmrgscf=-22.3305493297538
E_block2main=-22.3305444981 (running block2main directly with dmrg.conf)
For dmrgscf, I think the PySCF Hartree-Fock orbital may improve the accuracy. But I couldn't figure out why block2main has better accuracy than pyblock2. I wonder if you could help me resolve this question and provide me with some guidance to improve the pyblock2 interface's accuracy. Thank you very much in advance!

Please also see below for my Python script and the input data [ham_test_nosoc.h5.txt](https://github.com/block-hczhai/block2-preview/files/13415822/ham_test_nosoc.h5.txt) (it is an hdf5 file for h1e and h2e) and [dmrg.conf.txt](https://github.com/block-hczhai/block2-preview/files/13415860/dmrg.conf.txt):
```python
import numpy as np
from scipy.linalg import eig, eigh, inv
import h5py
from pyscf import tools, gto, scf, ao2mo, ci, lib , fci, dmrgscf
import os
dmrgscf.settings.BLOCKEXE = os.popen("which block2main").read().strip()
dmrgscf.settings.MPIPREFIX = ''#mpirun -n 1 --bind-to none'
from pyblock2.driver.core import DMRGDriver, SymmetryTypes
np.set_printoptions(suppress=True, precision=4)

fh5 = h5py.File('ham_test_nosoc.h5')
Utensor = fh5['Utensor'][...]
h1e = fh5['h1e'][...]
fh5.close()

nimp = Utensor.shape[0]
nbath = h1e.shape[0] - Utensor.shape[0]
ntot = h1e.shape[0]
print('nimp=', nimp, 'nbath=', nbath)

# DMRG bond dimension
maxM = 300

# test for block2 DMRG
driver = DMRGDriver(scratch="./tmp", symm_type=SymmetryTypes.SZ, n_threads=6)

driver.initialize_system(n_sites=ntot//2, n_elec=ntot//2, spin=0)

b = driver.expr_builder()

for i in range(ntot):
    for j in range(ntot):
        if abs(h1e[i,j])>1e-6:
            if i%2 == 0:
                b.add_term("cd", [i//2,j//2], h1e[i,j].real)
            elif i%2 == 1:
                b.add_term("CD", [i//2,j//2], h1e[i,j].real)

for i in range(nimp):
    for j in range(nimp):
        for k in range(nimp):
            for l in range(nimp):
                if abs(Utensor[i,k,j,l])>1e-6:
                    if i%2 ==1 and j%2 ==0 and l%2==1 and k%2==0: 
                       b.add_term("CcDd", [i//2,j//2,l//2,k//2], 0.5*Utensor[i,k,j,l].real)
                    elif i%2 ==1 and j%2 ==0 and l%2==0 and k%2==1: 
                       b.add_term("CcdD", [i//2,j//2,l//2,k//2], 0.5*Utensor[i,k,j,l].real)
                    elif i%2 ==0 and j%2 ==1 and l%2==1 and k%2==0: 
                       b.add_term("cCDd", [i//2,j//2,l//2,k//2], 0.5*Utensor[i,k,j,l].real)
                    elif i%2 ==0 and j%2 ==1 and l%2==0 and k%2==1: 
                       b.add_term("cCdD", [i//2,j//2,l//2,k//2], 0.5*Utensor[i,k,j,l].real)
                    elif i%2 ==0 and j%2 ==0 and l%2==0 and k%2==0:
                       b.add_term("ccdd", [i//2,j//2,l//2,k//2], 0.5*Utensor[i,k,j,l].real)
                    elif i%2 ==1 and j%2 ==1 and l%2==1 and k%2==1:
                       b.add_term("CCDD", [i//2,j//2,l//2,k//2], 0.5*Utensor[i,k,j,l].real)
                    else:
                       print(i,j,k,l)

mpo = driver.get_mpo(b.finalize(), iprint=0)

ket = driver.get_random_mps(tag="KET", bond_dim=maxM, nroots=1)

bond_dims = [100,200,300,300]+[300,300,300,300]#[maxM] * 8
noises = [1e-5]*4 + [1e-6]*4 + [0]
thrds = [1e-10]*8

energies = driver.dmrg(mpo, ket, n_sweeps=100, bond_dims=bond_dims, noises=noises, thrds=thrds, cutoff=0, iprint=1)

denMat_block2 = driver.get_1pdm(ket)
print(denMat_block2[0])
print(denMat_block2[1])
#assert(np.allclose(denMat_block2[0],denMat_block2[1], atol=1e-4))
dmup = (denMat_block2[0]+denMat_block2[1])/2.
denMat_block2 = np.kron(dmup,np.eye(2)) 
print('density matrix block2=')
print(denMat_block2)

# Hartree-Fock
mol = gto.M()
mol.nelectron = ntot//2
mol.incore_anyway = True
mf = scf.RHF(mol)
mf.max_cycle = 1000
mf.conv_tol = 1e-8#1e-12
mf.diis_space = 5#10
mf.diis_start_cycle = 5
mf.diis = True
mf.get_hcore = lambda *args: h1e[::2,::2].real
mf.get_ovlp = lambda *args: np.eye(ntot//2)
h2e = np.zeros((ntot//2,ntot//2,ntot//2,ntot//2))
h2e[:nimp//2,:nimp//2,:nimp//2,:nimp//2] = Utensor[::2,::2,1::2,1::2].real
mf._eri = ao2mo.restore(8, h2e, ntot//2) # 8-fold symmetry
tools.fcidump.from_integrals('FCIDUMP',h1e[::2,::2].real, h2e, ntot//2, ntot//2)
#mf._eri = h2e
mf.init_guess = '1e'
mf = mf.run()
C = mf.mo_coeff

#Test for dmrgscf
nmo = mf.mo_coeff.shape[1]
nelec = mol.nelec # this part report error when nelectron is odd
cisolver = dmrgscf.DMRGSCF(mf, nmo, nelec, maxM=maxM, tol=1e-8)
cisolver.fcisolver.runtimeDir = lib.param.TMPDIR
cisolver.fcisolver.scratchDirectory = lib.param.TMPDIR
cisolver.fcisolver.threads = int(os.environ.get("OMP_NUM_THREADS", 4))
cisolver.verbose = 4
print('using threads:',cisolver.fcisolver.threads)
cisolver.fcisolver.memory = int(mol.max_memory / 1000) # mem in GB
#cisolver.canonicalization = True
#cisolver.natorb = True
e0 = cisolver.kernel()[0]
dm1 = cisolver.fcisolver.make_rdm1(0, nmo, nelec)/2.
dmup = np.einsum('ai,bj,ij->ab', C, C, dm1)
denMat_dmrgscf = np.kron(dmup,np.eye(2))

#Test for FCI
cisolver = fci.direct_spin1.FCI()
evals, fcivecs = cisolver.kernel(h1e[::2,::2].real, h2e, ntot//2, ntot//2, nroots=1, verbose=4, max_cycle=2000)
dmup, dmdn = cisolver.make_rdm1s(fcivecs, ntot//2, ntot//2)
denMat_fci = np.kron(dmup,np.eye(2))
print('E_FCI=',evals)

print('density matrix dmrgscf=')
print(denMat_dmrgscf)
print('density matrix block2=')
print(denMat_block2)
print('density matrix FCI=')
print(denMat_fci)
print('maxdiff(denMat_block2 - denMat_fci)=')
print(np.max(np.abs(denMat_block2 - denMat_fci)))
print('maxdiff(denMat_dmrgscf - denMat_fci)=')
print(np.max(np.abs(denMat_dmrgscf - denMat_fci)))
```

**Comment by hczhai** [comment]
Hi, thanks for the detailed description of the problem.

You get different energies in different interfaces mainly because you used different spin symmetries.
1. For the python interface, you are using the non-spin-adapted mode, indicated by ``symm_type=SymmetryTypes.SZ``.
2. For the block2main and ``dmrgscf`` case, the default option is the spin-adapted mode.

The bond dimension $M=300$ spin-adapted MPS is more accurate than the $M=300$ non-spin-adapted MPS. But when you set a larger $M$, both of them will converge to the FCI number.

If you want to compare results in the non-spin-adapted mode, you can use your current python script (with is non-spin-adapted) and you need to add the keyword ``nonspinadapted`` in ``dmrg.conf`` to also do non-spin-adapted DMRG.

If you want to compare results in the spin-adapted mode, you keep the current ``dmrg.conf``, and in your python script, change the ``driver = DMRGDriver(...)`` part and the MPO building code to the following:

```python3
driver = DMRGDriver(scratch="./tmp", symm_type=SymmetryTypes.SU2, n_threads=6)
driver.initialize_system(n_sites=ntot//2, n_elec=ntot//2, spin=0)
driver.read_fcidump('FCIDUMP', pg='c1')
mpo = driver.get_qc_mpo(h1e=driver.h1e, g2e=driver.g2e, ecore=driver.ecore)
```

Then you will get spin-adapted results from the python interface.

If you want to do relativistic DMRG or Hamiltonians with spin-orbit-coupling terms, neither spin-adapted nor non-spin-adapted would work. You will need the general-spin mode (``SGFCPX``). See the script provided in my reply to your previous question.

**Comment by henhans** [comment]
Dear @hczhai, Thank you very much for your reply. I changed the symmetry type to SU2 using:
```python
driver = DMRGDriver(scratch="./tmp", symm_type=SymmetryTypes.SU2, n_threads=6)
```
But the calculation freezes at the MPO step
```python
mpo = driver.get_mpo(b.finalize(), iprint=0)
```
I wonder if you know what may be wrong in my script that causes the hanging of the calculation? Thank you!

**Comment by hczhai** [comment]
Hi, thanks for your feedback. When you build the Hamiltonian in the spin-adapted (SU2) mode, you need to use the spin-adapted expression of the Hamiltonian, and the syntax for the expression is different from that of the SZ case. This is explained in detail in the documentation: https://block2.readthedocs.io/en/latest/tutorial/hubbard.html#The-SU2-Mode. The example code for MPO construction using spin-adapted expression can be found in the implementation of ``driver.get_qc_mpo``: https://github.com/block-hczhai/block2-preview/blob/p0.5.3rc3/pyblock2/driver/core.py#L2332-L2345.

If you are not familiar with the SU2 terminologies, the recommendation is not to build Hamiltonians manually in the SU2 mode. Please use the SZ mode instead.

**Comment by henhans** [comment]
Got it. Thank you so much!
