### ISSUE TITLE
Using SZ mode with complex number

### ISSUE THREAD

**Issue by henhans** [block-hczhai/block2-preview#73]
Dear Developers,

I wonder if there is an option for running DMRG calculations with complex SZ mode?
This would be very helpful for some materials where the inversion symmetry is absent, and the Hamiltonian can be complex (without spin-orbit coupling). Thank you!

Best,
Tsung-Han

**Comment by hczhai** [comment]
This is supported via python interface: ``DMRGDriver(scratch="./tmp", symm_type=SymmetryTypes.SZ | SymmetryTypes.CPX, n_threads=4)``.

**Comment by henhans** [comment]
Thank you very much!
