### ISSUE TITLE
"RuntimeError: No job for this processor" error in DMRG-NEVPT2

### ISSUE THREAD

**Issue by 1234zou** [block-hczhai/block2-preview#74]
I've read the issue #61 and found that an OpenMP-parallelized DMRG calculation using pyblock2 is much faster than an MPI one (on a single node). However, I'm wondering that how to write the DMRG-NEVPT2 input in such case, since DMRG is OpenMP-parallelized, but DMRG-NEVPT2 in PySCF requires `from mpi4py import MPI`.

I've tried this input
```
from pyscf import gto, scf, mcscf, dmrgscf, mrpt, lib

dmrgscf.settings.MPIPREFIX = ''
nproc = 64
lib.num_threads(nproc)

mol = gto.M()
mol.atom = '''
H    0.0     0.0   -1.5
H    0.0     0.0   -3.0
H    0.0     0.0   -4.5
H    0.0     0.0   -6.0
H    0.0     0.0   -7.5
H    0.0     0.0   -9.0
H    0.0     0.0  -10.5
H    0.0     0.0    0.0
H    0.0     0.0    1.5
H    0.0     0.0    3.0
H    0.0     0.0    4.5
H    0.0     0.0    6.0
H    0.0     0.0    7.5
H    0.0     0.0    9.0
H    0.0     0.0   10.5
H    0.0     0.0   12.0
'''

mol.basis = 'STO-6G'
mol.charge = 0
mol.spin = 0
mol.verbose = 4
mol.build(parse_arg=False)

mf = scf.RHF(mol)
mf.kernel()

mc = mcscf.CASCI(mf,16, (8,8))
mc.fcisolver = dmrgscf.DMRGCI(mol, maxM=1000)
mc.max_memory = 126000 # MB
mc.fcisolver.threads = nproc
mc.fcisolver.memory = 76 # GB
mc.fcisolver.max_cycle = 200
mc.verbose = 5
mc.kernel()

mrpt.NEVPT(mc).compress_approx(maxM=1000).kernel()
```

but got the following error in the DMRG-NEVPT2 step 
```
/public/home/jxzou/software/pyscf-2.4.0/pyscf/dft/libxc.py:771: UserWarning: Since PySCF-2.3, B3LYP (and B3P86) are changed to the VWN-RPA variant, corresponding to the original definition by Stephens et al. (issue 1480) and the same as the B3LYP functional in Gaussian. To restore the VWN5 definition, you can put the setting "B3LYP_WITH_VWN5 = True" in pyscf_conf.py
  warnings.warn('Since PySCF-2.3, B3LYP (and B3P86) are changed to the VWN-RPA variant, '
Traceback (most recent call last):
  File "/public/home/jxzou/software/dmrgscf/pyscf/dmrgscf/nevpt_mpi.py", line 509, in <module>
    nevpt_integral_mpi(sys.argv[1],sys.argv[2],sys.argv[3],sys.argv[4])
  File "/public/home/jxzou/software/dmrgscf/pyscf/dmrgscf/nevpt_mpi.py", line 282, in nevpt_integral_mpi
    ncas, partial_core, partial_virt = _write_integral_file(mc_chkfile, nevpt_scratch_mpi, comm)
  File "/public/home/jxzou/software/dmrgscf/pyscf/dmrgscf/nevpt_mpi.py", line 429, in _write_integral_file
    raise RuntimeError('No job for this processor.  It may block MPI.COMM_WORLD.barrier')
RuntimeError: No job for this processor.  It may block MPI.COMM_WORLD.barrier
```

It seems that the problem is caused by MPI parallelism. Maybe not the problem of PySCF/pyblock2, but the problem of SLURM script. For more details please see the attached input /output files
[DMRG-NEVPT2_test.zip](https://github.com/block-hczhai/block2-preview/files/13896628/DMRG-NEVPT2_test.zip)
(there is nothing printed by SLURM, so there is no file about SLURM output in the .zip package above)

Thanks.

**Comment by hczhai** [comment]
Hi, thanks for providing the details of the problem.

The error message ``No job for this processor`` was caused by the fact that you have in total 16 orbitals and all of them are included in the CASCI active space (not related to MPI). The PT2 subspace is null. So the script can work correctly if you set the correct active space.

If you want to use MPI parallelization just for NEVPT2, you can insert lines between ``mc.kernel()`` and ``mrpt.NEVPT(mc).compress_approx(maxM=1000).kernel()``:

```python3
... ...
mc.kernel()

dmrgscf.settings.MPIPREFIX = 'mpirun -n 64'
lib.num_threads(1)
mc.fcisolver.threads = 1
mc.fcisolver.memory = 76 / 64 # GB
mc.fcisolver.mpiprefix = 'mpirun -n 64'

mrpt.NEVPT(mc).compress_approx(maxM=1000).kernel()
```

To prevent the error ``No job for this processor``, the number of core and virtual PT2 orbitals should be equal to or larger than the number of MPI processors. If this cannot be satisfied, you can use mixed MPI / openMP parallelization, for example, ``mpiprefix = 'mpirun -n 4 --bind-to none'; mc.fcisolver.threads = 16``. Alternatively, you can simply use just 1 MPI processor for everything, as what you already did in your script. This is also the recommended usage illustrated in the documentation https://block2.readthedocs.io/en/latest/user/dmrg-scf.html#dmrg-sc-nevpt2.

**Comment by 1234zou** [comment]
Oh, my stupid mistake, I forgot to use a larger basis set. Thanks for your detailed explanations. I have two more questions:
(1) what is the difference between `dmrgscf.settings.MPIPREFIX` and `mc.fcisolver.mpiprefix`?
(2) For very large active space, `mrpt.NEVPT(mc).compress_approx(maxM=N).kernel()` should be used to save time. But how large is it? Do you have any experience? It seems that `mrpt.NEVPT(mc).kernel()` works for DMRG(16,16).

**Comment by hczhai** [comment]
(1) The ``npvpt2`` part will only check ``mc.fcisolver.mpiprefix`` so changing ``dmrgscf.settings.MPIPREFIX`` after the creation of the ``mc`` object will have no effect.
(2) The bottleneck of ``mrpt.NEVPT(mc).kernel()`` is the storage of 4pdm (in memory). For CAS(16,16) it needs only 32 GB memory. For CAS(24,24), it needs 820 GB memory (cannot be alleviated by MPI).

**Comment by 1234zou** [comment]
Great!

**Comment by 1234zou** [comment]
By the way, which of the following cases represent the words `the number of core and virtual PT2 orbitals should be equal to or larger than the number of MPI processors` best?
(1) n_core + nvir >= nproc;
(2) n_core*n_vir >= nproc;
(3) both n_core and n_vir >= nproc.

**Comment by hczhai** [comment]
(1). See https://github.com/pyscf/dmrgscf/blob/master/pyscf/dmrgscf/nevpt_mpi.py#L387-L429. Note that this is not a limitation caused by ``block2`` or ``pyblock2``.
