### ISSUE TITLE
forte

### ISSUE THREAD

**Issue by chburger** [block-hczhai/block2-preview#77]
Great to see that integrated forte. Unfortunately my make stopped at

/home/psi4/forte/forte/helpers/iterative_solvers.cc: In member function ‘forte::SolverStatus forte::DavidsonLiuSolver::update()’:
/home/psi4/forte/forte/helpers/iterative_solvers.cc:211:21: error: ‘schmidt_add’ was not declared in this scope
  211 |                 if (schmidt_add(b_->pointer(), basis_size_, size_, f->pointer()[k])) {

Do you have advice? This was with gcc-10 and 11 with gcc-13 there was an error elsewhere.

**Comment by hczhai** [comment]
Thanks for pointing out the issue. Please retry following the updated documentation https://block2.readthedocs.io/en/latest/user/forte.html.

**Comment by chburger** [comment]
Thanks so much!!!!!!!!!!!!!! - finally/eventually I have a working version of Forte which is even improved by your great block2 code!  
Still this was quite a fight with python versions & modules, the right cmake, libs (eigen, mkl, hdf5, boost) and the right version of the C-compiler and psi4. Therefore - could I convince you to prepare/provide a Conda package?

**Comment by hczhai** [comment]
Thanks for the feedback.

Considering that none of the complexities you mentioned (python versions, cmake versions, compiler versions, eigen, hdf5, boost, mkl, and psi4) is the dependence required by ``block2`` (``block2`` can be built with or without MKL). I do not think this is an issue of ``block2``.
