### ISSUE TITLE
DDMRG in dmrgscf

### ISSUE THREAD

**Issue by JangidBhavnesh** [block-hczhai/block2-preview#87]
Is there implementation of using DDMRG, after using mcscf (with fcisolver=dmrgscf) solver of the pyscf?

**Comment by hczhai** [comment]
The effect of DMRGSCF/CASSCF is only to generate a set of optimized orbitals, stored as ``mc.mo_coeff``. You can do ``mf.mo_coeff = mc.mo_coeff`` and then use ``itg.get_rhf_integrals(mf, ncore=mc.ncore, ncas=mc.ncas, ...)`` to get the integrals (see https://block2.readthedocs.io/en/latest/tutorial/qc-hamiltonians.html#Spin-Restricted-Integrals) in the optimized orbitals, and then use ``DMRGDriver.multiply`` to do dynamical DMRG. See https://block2.readthedocs.io/en/latest/api/pyblock2.html#pyblock2.driver.core.DMRGDriver.multiply.
