### ISSUE TITLE
Energy floats as MaxM increases

### ISSUE THREAD

**Issue by white-in-black** [block-hczhai/block2-preview#88]
when i calculate (H2O)2/cc-pVDZ system, use DMRGCI(42o, 8e), i find that when i increase the value of MaxM, the result of energy values float several times, the result i calculated as following and python code is in DMRG.zip. i want you help to solve this problem. Looking forward to your reply, thank you.
[DMRG.zip](https://github.com/block-hczhai/block2-preview/files/14905585/DMRG.zip)

MaxM | DMRG energy
-- | --
1000 | -151.59203139
1500 | -151.60819211
2000 | -151.59203143
2500 | -151.59203150
3000 | -151.60819211
3500 | -151.59203150
4000 | -151.59203148

**Comment by hczhai** [comment]
Thanks for reporting the problem.

DMRG, like many other numerical quantum chemistry algorithms, can get stuck in excited states or local minima. For your case you can add a line ``mc.fcisolver.nroots = 2`` setting the number of roots to 2 or a larger number and this will increase the probability to find the true ground state.

**Comment by white-in-black** [comment]
thanks for your reply. i will try it soon. and if i use nroots＞1, does it use state average to get a reasonable result?



---Original---
From: "Huanchen ***@***.***&gt;
Date: Tue, Apr 9, 2024 00:46 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [block-hczhai/block2-preview] Energy floats as MaxM increases(Issue #88)




 
Thanks for reporting the problem.
 
DMRG, like many other numerical quantum chemistry algorithms, can get stuck in excited states or local minima. For your case you can add a line mc.fcisolver.nroots = 2 setting the number of roots to 2 or a larger number and this will increase the probability to find the true ground state.

**Comment by hczhai** [comment]
> does it use state average to get a reasonable result?

It will use state-averaged DMRG.

**Comment by white-in-black** [comment]
thanks for your reply. for question of state average, i mean when i use nroots＝n ＞1, the final result is from whether state averaged-DMRG by thess n roots or the lowest value of these n roots? if i want to use state averaged-DMRG, do i need to add other codes into .py file



---Original---
From: "Huanchen ***@***.***&gt;
Date: Tue, Apr 9, 2024 08:27 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [block-hczhai/block2-preview] Energy floats as MaxM increases(Issue #88)




  
does it use state average to get a reasonable result?
  
It will use state-averaged DMRG.

**Comment by hczhai** [comment]
When you use ``nroots`` larger than 1, then at the end of CASCI, it will print multiple energies. You just need to take the lowest one and ignore the others. The lowest energy is the energy for the ground state. So for your purpose, this state-averaged DMRG has no side effects.

You do not need to add anything other than ``mc.fcisolver.nroots = 2``.

**Comment by white-in-black** [comment]
i got it. thanks a lot for your patient reply
ψ(｀∇´)ψ！



---Original---
From: "Huanchen ***@***.***&gt;
Date: Tue, Apr 9, 2024 08:56 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [block-hczhai/block2-preview] Energy floats as MaxM increases(Issue #88)




 
When you use nroots larger than 1, then at the end of CASCI, it will print multiple energies. You just need to take the lowest one and ignore the others. The lowest energy is the energy for the ground state. So for your purpose, this state-averaged DMRG has no side effects.
 
You do not need to add anything other than mc.fcisolver.nroots = 2.
