### ISSUE TITLE
Segmentation fault from twopdm flag

### ISSUE THREAD

**Issue by rhkim79** [block-hczhai/block2-preview#9]
I have tried to run DMRG for the 2D Hubbard model(6 by 6, U=8.0, nelec=32e-) with a smaller bond dimension(100). However, it returns a segmentation fault error after building 2pdm(see log.txt) regardless of flags(e.g. nonspinadapted/noreorder). On the other hand, it works without error if I remove the twopdm flag. I have tested on a large memory system(200G/400G/800G), but it could not resolve this issue.

Here I attached a minimal working example for the problematic case. I would appreciate it if you could check it and share your feedback.

To run the mwe, execute as follows:
block2main mwe/dmrg.conf.000

[mwe.tar.gz](https://github.com/block-hczhai/block2-preview/files/8508930/mwe.tar.gz)
[log.txt](https://github.com/block-hczhai/block2-preview/files/8508931/log.txt)

**Comment by hczhai** [comment]
Thanks for pointing out the issue. This is related to the stack size. As indicated in the note in the documentation https://block2.readthedocs.io/en/latest/user/basic.html#n-particle-reduced-density-matrix:

> A large local stack may be required for this calculation. Use the command ``ulimit -s unlimited`` to allow a large local stack.

it can be solved by calling ``ulimit -s unlimited`` before calling ``block2main``. You may:

either (1) add ``ulimit -s unlimited`` in your ``~/.bashrc``. Then ``source ~/.bashrc``.
or (2) add ``ulimit -s unlimited`` in your submission script, so it will be like:

    ulimit -s unlimited
    block2main dmrg.conf > dmrg.out

Please let me know if you find some additional problems.

**Comment by rhkim79** [comment]
Oh. I forgot to include that in my issue. Yes. I have set
ulimit -s unlimited 
for all the experiment I have mentioned over.

**Comment by hczhai** [comment]
Hi, in the following google colab notebook https://colab.research.google.com/drive/1VDz1MSZj78IpApGLQLgk6MDddwbHUqQ_?usp=sharing , using your attached files, with ``ulimit -s unlimited`` the calculation can run normally without any problem.

Regarding the screenshot, you have to type ``ulimit -s`` or ``ulimit -a`` to see the effect.
In my macOS, after ``ulimit -s unlimited`` and ``ulimit -s`` I got ``65532`` (KB), so this is about 65 MB. For a 2pdm with 36 orbitals, we need a stack of ``36*36*36*36*8*8 B = 103 MB``. So the hard limit of stack size 65 MB in macOS does not allow this calculation.

But we normally run ``block2`` in hpc (Linux), and there is indeed unlimited stack size. I can change the code a little bit to remove this stack requirement but let me first have some more understanding of your case:

What do you get from ``ulimit -s``? What is your operating system?

**Comment by rhkim79** [comment]
Thanks for the example. I'm using WSL, Ubuntu 20.04 on Windows. Since it is not allowed to apply
`ulimit -s unlimited `
directly, I set by 
`sudo prlimit --stack=unlimited --pid $$; ulimit -s unlimited`
Then the ulimit -a shows
![image](https://user-images.githubusercontent.com/50161497/163907073-33693a63-de5b-4c8d-a85a-921779d9c99f.png)
But it still returns the segmentation fault
![image](https://user-images.githubusercontent.com/50161497/163907331-90e89ea6-0c69-4cb7-a50e-41a2af3aa52a.png)
Let me check it in the google cloud too.

**Comment by rhkim79** [comment]
OK. It seems that the WSL was the problem. I have tried to test on google cloud and it does not return the segmentation fault. Considering that WSL is a local VM, the stacksize would be limited both the VM itself and Windows. 
Thank you for the kind answer!

**Comment by hczhai** [comment]
Thanks for the detailed response. I think making the code working in macOS and WSL over Windows may still be important for some users.
So in this new commit https://github.com/block-hczhai/block2-preview/commit/f67a087cd8a5d1d971d7de2df488cdd9e5e269f9 the stack size restriction for 2pdm should be fixed.
If you compile ``block2`` from source you can update the source code and re-compile.
If you get ``block2`` from ``pip``, the updated version will be version 0.5.0, but it will take some time to generate the package. You can try ``pip install block2==0.5.0`` after 6 to 12 hours.

With the updated code, there should be no need to ``ulimit`` and there should not be any ``segfault`` (even in macOS or WSL).
Please let me know if the error can be fixed by this update.

**Comment by rhkim79** [comment]
Sure. I'll try it tomorrow and share the result.

**Comment by rhkim79** [comment]
Now it works well on WSL, too. Thank you!
